const DEFAULT_CRESTS=[
  "imagenes/escudos_equipos/atletico_lesterol_512x512.png",
  "imagenes/escudos_equipos/aubameyang_y_10_mas_transparent_512x512.png",
  "imagenes/escudos_equipos/mariscos_recio_transparent_512x512.png",
  "imagenes/escudos_equipos/maccabi_de_levantar_transparent_512x512.png",
  "imagenes/escudos_equipos/recreativo_de_juerga_transparent_512x512.png",
  "imagenes/escudos_equipos/renacidos_cf_transparent_512x512.png",
  "imagenes/escudos_equipos/sporting_de_finidi_transparent_v2_512x512.png",
  "imagenes/escudos_equipos/moleiros_team_transparent_512x512.png",
  "imagenes/escudos_equipos/los_pridecines_transparent_v5_512x512.png",
  "imagenes/escudos_equipos/ozempic_de_leon_transparent_512x512.png",
  "imagenes/escudos_equipos/equipo_11_transparent_512x512.png",
  "imagenes/escudos_equipos/aston_birra_transparent_512x512.png"
];
const DEFAULT_CLUBS=Array.from({length:12},(_,i)=>({
  name:i===0?"Atlético Lesterol":`Equipo ${i+1}`,
  manager:"Por asignar",
  motto:"La historia está a punto de escribirse.",
  points:0,
  pointsApertura:0,
  pointsClausura:0,
  pointsGeneral:0,
  crest:DEFAULT_CRESTS[i],
  kit:"",
  badges:Array.from({length:4},()=>({name:"",image:""})),
  players:[],
  matchdays:Array.from({length:38},()=>0),
  playerHistory:[],
  lineups:Array.from({length:38},()=>Array.from({length:11},()=>({name:"",points:0}))),
  formations:Array.from({length:38},()=>"1-4-3-3"),
  transfers:[],
  initialBalance:100000000,
  titleWins:Array(5).fill(0)
}));
const CUP_STAGE_SPECS=[{key:"preliminary",title:"RONDA PREVIA",count:6,prefix:"ELIMINATORIA"},{key:"quarterfinals",title:"CUARTOS DE FINAL",count:4,prefix:"CUARTO"},{key:"semifinals",title:"SEMIFINALES",count:2,prefix:"SEMIFINAL"},{key:"final",title:"FINAL",count:1,prefix:"GRAN FINAL"}];
const COMPETITION_NAMES=["Liga Apertura","Liga Clausura","Liga Ronda Final","Copa Apertura","Copa Clausura"];
function emptyCup(){return {bestLosers:[null,null],stages:Object.fromEntries(CUP_STAGE_SPECS.map(stage=>[stage.key,Array.from({length:stage.count},()=>({teams:[null,null],scores:[[null,null],[null,null]],date:"",winner:null}))]))}}
function mergeCup(saved={}){const base=emptyCup();return {...base,...saved,bestLosers:Array.from({length:2},(_,i)=>saved.bestLosers?.[i]??null),stages:Object.fromEntries(CUP_STAGE_SPECS.map(stage=>[stage.key,Array.from({length:stage.count},(_,i)=>{const tie=saved.stages?.[stage.key]?.[i]||{};return {...base.stages[stage.key][i],...tie,teams:Array.from({length:2},(_,t)=>tie.teams?.[t]??null),scores:Array.from({length:2},(_,leg)=>Array.from({length:2},(_,t)=>tie.scores?.[leg]?.[t]??null))}})]))}}
const DEFAULT_DATA={league:"RONDA FINAL",season:"2026 / 2027",welcome:"",faqs:[],players:[],clubs:DEFAULT_CLUBS,cups:{apertura:emptyCup(),clausura:emptyCup()},leaguesCompleted:{apertura:false,clausura:false,general:false},draw:{enabled:false,title:"Sorteo oficial",selection:null,participants:[],pairs:[],timestamp:"",resetToken:"20260728-reset-1"}};
const STORAGE_KEY="universoFantasyData";
const PASSWORD_KEY="universoFantasyPassword";
let data=loadData();
let currentClubIndex=0;
let adminClubIndex=0;

function loadData(){
  try{
    const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");
    let clubs=saved.clubs;
    if(!clubs&&Array.isArray(saved.teams)) clubs=saved.teams.map(name=>({name,manager:"Por asignar",points:0,crest:""}));
    clubs=DEFAULT_CLUBS.map((fallback,i)=>{const club={...fallback,...(clubs?.[i]||{})};if(club.pointsGeneral===0&&club.points)club.pointsGeneral=club.points;club.badges=Array.from({length:4},(_,b)=>({...fallback.badges[b],...(club.badges?.[b]||{})}));club.titleWins=Array.from({length:5},(_,t)=>Math.max(0,Math.min(10,Number(club.titleWins?.[t])||0)));club.players=Array.isArray(club.players)?club.players.filter(player=>player?.name):[];club.matchdays=Array.from({length:38},(_,j)=>Number(club.matchdays?.[j])||0);club.playerHistory=Array.isArray(club.playerHistory)?club.playerHistory.map(player=>({name:player.name||"",entryDate:player.entryDate||"",exitDate:player.exitDate||"",legacyPoints:Number(player.legacyPoints??player.pointsPerMatchday??player.points)||0,matchdayPoints:Array.from({length:38},(_,j)=>player.matchdayPoints?.[j]??null)})):[];club.lineups=Array.from({length:38},(_,j)=>Array.from({length:11},(_,p)=>({name:club.lineups?.[j]?.[p]?.name||"",points:Number(club.lineups?.[j]?.[p]?.points)||0})));club.formations=Array.from({length:38},(_,j)=>club.formations?.[j]||"1-4-3-3");club.transfers=Array.isArray(club.transfers)?club.transfers:[];club.initialBalance=Number.isFinite(Number(club.initialBalance))&&Number(club.initialBalance)>0?Number(club.initialBalance):100000000;return club});
    const migratedPlayers=Array.isArray(saved.players)?saved.players:[];
    clubs.forEach((club,clubIndex)=>club.players.forEach(old=>{if(!migratedPlayers.some(player=>playerKey(player.name)===playerKey(old.name)))migratedPlayers.push({id:crypto.randomUUID(),name:old.name,position:old.position||"Medio",marketValue:numericPrice(old.marketValue),clause:numericPrice(old.clause),clubId:clubIndex,createdAt:new Date().toISOString(),transferCount:0,totalPaid:0,stints:[{clubId:clubIndex,from:"",to:"",points:Number(old.points)||0,price:0,type:"Migración"}]})}));
    const players=migratedPlayers.map(player=>({...player,id:player.id||crypto.randomUUID(),clubId:player.clubId===null||player.clubId===undefined?null:Number(player.clubId),position:player.position||"Medio",marketValue:numericPrice(player.marketValue),clause:numericPrice(player.clause),transferCount:Number(player.transferCount)||0,totalPaid:Number(player.totalPaid)||0,stints:Array.isArray(player.stints)?player.stints:[]}));
    clubs.forEach((club,i)=>club.players=players.filter(player=>player.clubId===i));
    const merged={...DEFAULT_DATA,...saved,players,clubs};delete merged.news;merged.faqs=Array.isArray(saved.faqs)?saved.faqs.map(item=>({id:item.id||crypto.randomUUID(),question:String(item.question||""),answer:String(item.answer||"")})):[];merged.cups={apertura:mergeCup(saved.cups?.apertura),clausura:mergeCup(saved.cups?.clausura)};merged.leaguesCompleted={...DEFAULT_DATA.leaguesCompleted,...(saved.leaguesCompleted||{})};merged.draw={...DEFAULT_DATA.draw,...(saved.draw||{})};if(saved.draw?.resetToken!==DEFAULT_DATA.draw.resetToken)merged.draw={...merged.draw,participants:[],pairs:[],timestamp:"",resetToken:DEFAULT_DATA.draw.resetToken};if(merged.season==="2026 / 27")merged.season="2026 / 2027";if(merged.league==="UNIVERSO")merged.league="RONDA FINAL";return merged;
  }catch{return {...DEFAULT_DATA,clubs:DEFAULT_CLUBS.map(c=>({...c}))}}
}
function esc(value){const d=document.createElement("div");d.textContent=value;return d.innerHTML}
function initials(name,index){const words=name.trim().split(/\s+/);return words.length>1?words.slice(0,2).map(w=>w[0]).join("").toUpperCase():(name.slice(0,2)||`E${index+1}`).toUpperCase()}
function crestMarkup(club,index,className="crest"){
  return club.crest?`<img class="${className} has-image" src="${esc(club.crest)}" alt="Escudo de ${esc(club.name)}">`:`<span class="${className} ${className==='mini-crest'?'mini-fallback':''}">${esc(initials(club.name,index))}</span>`;
}
function standingsMarkup(pointsField){
  const ranked=data.clubs.map((club,index)=>({club,index})).sort((a,b)=>Number(b.club[pointsField])-Number(a.club[pointsField])||a.index-b.index);
  return ranked.map(({club,index},position)=>`<a class="standing-row" href="#club/${index}" data-club="${index}"><div class="standing-club"><span class="position">${String(position+1).padStart(2,"0")}</span>${crestMarkup(club,index,"mini-crest")}<span class="standing-name"><strong>${esc(club.name)}</strong><small>Manager · ${esc(club.manager)}</small></span></div><span class="standing-points"><b>${Number(club[pointsField])||0}</b><small>PTS</small></span></a>`).join("");
}
function matchdayStandingsMarkup(matchday){const ranked=data.clubs.map((club,index)=>({club,index,points:Number(club.matchdays[matchday])||0})).sort((a,b)=>b.points-a.points||a.index-b.index);return ranked.map(({club,index,points},position)=>`<a class="standing-row" href="#club/${index}" data-club="${index}"><div class="standing-club"><span class="position">${String(position+1).padStart(2,"0")}</span>${crestMarkup(club,index,"mini-crest")}<span class="standing-name"><strong>${esc(club.name)}</strong><small>Manager · ${esc(club.manager)}</small></span></div><span class="standing-points"><b>${points}</b><small>PTS</small></span></a>`).join("")}
function renderLeagueMatchday(kind,matchday){const isApertura=kind==="apertura",start=isApertura?0:19,end=isApertura?19:38,index=Math.max(start,Math.min(end-1,Number(matchday)||start)),select=document.getElementById(`${kind}MatchdaySelect`);select.innerHTML=Array.from({length:end-start},(_,offset)=>{const jornada=start+offset;return `<option value="${jornada}" ${jornada===index?"selected":""}>Jornada ${jornada+1}</option>`}).join("");document.getElementById(`${kind}MatchdayList`).innerHTML=matchdayStandingsMarkup(index)}
function compactStandingsMarkup(pointsField){const ranked=data.clubs.map((club,index)=>({club,index})).sort((a,b)=>Number(b.club[pointsField])-Number(a.club[pointsField])||a.index-b.index);return ranked.map(({club,index},position)=>`<a class="compact-standing-row" href="#club/${index}" data-club="${index}"><span class="compact-position">${String(position+1).padStart(2,"0")}</span>${club.crest?`<img class="compact-crest" src="${esc(club.crest)}" alt="">`:`<span class="compact-crest compact-fallback">${esc(initials(club.name,index))}</span>`}<strong class="compact-name">${esc(club.name)}</strong><span class="compact-points">${Number(club[pointsField])||0}<small>PTS</small></span></a>`).join("")}
function clubName(index,fallback="Equipo por sortear"){return index===null||index===undefined?fallback:(data.clubs[index]?.name||fallback)}
function scoreText(value){return value===null||value===""?"—":Number(value)}
function cupTotal(tie,team){const scores=[tie.scores[0][team],tie.scores[1][team]],hasScore=scores.some(value=>value!==null&&value!=="");return hasScore?scores.reduce((sum,value)=>sum+(Number(value)||0),0):null}
function cupTieMarkup(label,tie){const totals=[cupTotal(tie,0),cupTotal(tie,1)],leader=totals[0]!==null&&totals[1]!==null&&totals[0]!==totals[1]?totals[0]>totals[1]?0:1:null;return `<article class="cup-tie"><div class="cup-tie-head"><span>${label}</span><small>${esc(tie.date||"FECHAS PENDIENTES")}</small></div>${[0,1].map(team=>`<div class="cup-team ${leader===team?"cup-team-leading":""}">${tie.teams[team]!==null?crestMarkup(data.clubs[tie.teams[team]],tie.teams[team],"cup-team-crest"):`<i>?</i>`}<strong>${esc(clubName(tie.teams[team]))}</strong><b>IDA <em>${scoreText(tie.scores[0][team])}</em><br>VUELTA <em>${scoreText(tie.scores[1][team])}</em></b><span class="cup-total"><small>GLOBAL</small><em>${scoreText(totals[team])}</em></span></div>`).join("")}<div class="cup-winner">CLASIFICADO · <strong>${esc(clubName(tie.winner,"POR DECIDIR"))}</strong></div></article>`}
function cupStageMarkup(number,spec,cup){return `<section class="cup-stage ${spec.key}"><div class="cup-stage-title"><span>${number}</span><div><small>${spec.key==="final"?"PARTIDO ÚNICO":"DOBLE PARTIDO"}</small><h3>${spec.title}</h3></div></div><div class="cup-ties">${cup.stages[spec.key].map((tie,i)=>cupTieMarkup(`${spec.prefix} ${i+1}`,tie)).join("")}</div></section>`}
function cupScheduleMarkup(key){const schedule=key==="apertura"?{name:"APERTURA",rounds:["JORNADAS 3 Y 4","JORNADAS 7 Y 8","JORNADAS 11 Y 12","JORNADA 14"]}:{name:"CLAUSURA",rounds:["JORNADAS 21 Y 22","JORNADAS 25 Y 26","JORNADAS 30 Y 31","JORNADA 34"]};return `<section class="cup-schedule"><header><small>FECHAS PREVISTAS</small><h3>CALENDARIO · COPA ${schedule.name}</h3></header><div class="cup-schedule-rounds"><article><span>OCTAVOS</span><strong>${schedule.rounds[0]}</strong><small>IDA · VUELTA</small></article><article><span>CUARTOS</span><strong>${schedule.rounds[1]}</strong><small>IDA · VUELTA</small></article><article><span>SEMIFINALES</span><strong>${schedule.rounds[2]}</strong><small>IDA · VUELTA</small></article><article class="cup-schedule-final"><span>FINAL</span><strong>${schedule.rounds[3]}</strong><small>PARTIDO ÚNICO</small></article></div><p class="cup-schedule-note"><b>IMPORTANTE</b> No se tendrán en cuenta los partidos aplazados a una fecha posterior a la fecha oficial de cada jornada. Sí serán válidos los partidos adelantados.</p></section>`}
function renderCupFormats(){document.querySelectorAll(".cup-format").forEach(container=>{const key=container.dataset.cup.includes("Apertura")?"apertura":"clausura",cup=data.cups[key],champion=cup.stages.final[0].winner;container.innerHTML=`<section class="cup-rules cup-system"><header><small>SISTEMA DE COMPETICIÓN</small><h3>ASÍ FUNCIONA LA COPA</h3><p>Cada eliminatoria se decide con los puntos fantasy obtenidos por los equipos en las jornadas asignadas.</p></header><div class="cup-system-grid"><article><b>01</b><strong>PARTIDO DE IDA</strong><p>El resultado será la puntuación conseguida por cada equipo en una jornada concreta.</p></article><article><b>02</b><strong>PARTIDO DE VUELTA</strong><p>Se disputará con la puntuación de la jornada inmediatamente siguiente.</p></article><article><b>03</b><strong>RESULTADO GLOBAL</strong><p>Pasará de ronda el equipo que sume más puntos entre la ida y la vuelta.</p></article><article><b>04</b><strong>DESEMPATE POR GOLES</strong><p>Si el global termina empatado, se tendrán en cuenta los goles marcados durante esas dos jornadas.</p></article><article><b>05</b><strong>REPESCA EN OCTAVOS</strong><p>También avanzarán los dos mejores perdedores: los que hayan sumado más puntos entre los equipos eliminados.</p></article><article class="single-match"><b>06</b><strong>FINAL A PARTIDO ÚNICO</strong><p>El título se decidirá con la puntuación obtenida en una sola jornada.</p></article></div></section>${cupScheduleMarkup(key)}${cupStageMarkup("01",CUP_STAGE_SPECS[0],cup)}<section class="qualification-strip qualification-new"><div><small>CLASIFICAN A CUARTOS</small><strong>6 GANADORES</strong></div><i>+</i><div><small>REPESCA</small><strong>${cup.bestLosers.map(i=>esc(clubName(i,"POR DECIDIR"))).join(" · ")}</strong></div><i>=</i><div class="qualification-total"><small>CUADRO FINAL</small><strong>8 EQUIPOS</strong></div></section>${CUP_STAGE_SPECS.slice(1).map((spec,i)=>cupStageMarkup(String(i+2).padStart(2,"0"),spec,cup)).join("")}<section class="cup-champion"><span>★</span><small>CAMPEÓN DE ${esc(container.dataset.cup.toUpperCase())}</small><strong>${esc(clubName(champion,"POR DECIDIR"))}</strong><p>La copa espera dueño.</p></section>`})}
function positionCode(position){return {Portero:"POR",Defensa:"DEF",Medio:"MED",Delantero:"DEL"}[position]||"MED"}
function positionClass(position){return {Portero:"gk",Defensa:"df",Medio:"mf",Delantero:"fw"}[position]||"mf"}
function squadMarkup(club){return club.players.map((player,i)=>`<tr class="${player.name?'':'empty-player'}"><td class="squad-number">${String(i+1).padStart(2,"0")}</td><td class="player-name">${esc(player.name||`Jugador ${i+1}`)}</td><td><span class="position-tag ${positionClass(player.position)}">${positionCode(player.position)}</span></td><td class="money-value">${esc(player.marketValue||"—")}</td><td class="money-value">${esc(player.clause||"—")}</td><td class="points-value">${Number(player.points)||0}</td></tr>`).join("")}
function playerPoints(player){return (player.stints||[]).reduce((sum,stint)=>sum+(Number(stint.points)||0),0)}
function currentStint(player){return [...(player.stints||[])].reverse().find(stint=>stint.clubId===player.clubId&&!stint.to)}
function playersEditorMarkup(club){return `<details class="squad-editor" open><summary>Plantilla asignada · ${club.players.length}/18</summary><p class="players-help">La plantilla se gestiona desde el registro global de jugadores.</p><div class="players-editor">${club.players.length?club.players.map((player,p)=>`<div class="player-editor-row global-roster-row"><span>${String(p+1).padStart(2,"0")}</span><strong>${esc(player.name)}</strong><span class="position-tag ${positionClass(player.position)}">${positionCode(player.position)}</span><span>${formatMoney(player.marketValue)}</span><span>${formatMoney(player.clause)}</span><b>${playerPoints(player)} PTS</b></div>`).join(""):`<p class="players-help">Sin jugadores asignados.</p>`}</div></details>`}
function clubBalance(club){return (Number(club.initialBalance)||100000000)+club.transfers.reduce((sum,item)=>sum+(item.type==="Vendido"||item.type==="Ingreso"?numericPrice(item.price):-numericPrice(item.price)),0)}
function playerClubOptions(selected){return `<option value="" ${selected===null?"selected":""}>Agente libre</option>`+data.clubs.map((club,i)=>`<option value="${i}" ${selected===i?"selected":""}>${esc(club.name)} (${club.players.length}/18)</option>`).join("")}
function playerAdminRow(player){const stint=currentStint(player),days=stint?historyDays(stint.from,""):null;return `<div class="global-player-row" data-global-player="${esc(player.id)}"><div><strong>${esc(player.name)}</strong><small>${player.clubId===null?"AGENTE LIBRE":esc(data.clubs[player.clubId]?.name||"")} · ${Number(player.transferCount)||0} traspasos · ${days??0} días · ${playerPoints(player)} pts · pagado ${formatMoney(player.totalPaid)}</small></div><label>Posición<select data-global-field="position">${["Portero","Defensa","Medio","Delantero"].map(pos=>`<option ${player.position===pos?"selected":""}>${pos}</option>`).join("")}</select></label><label>Valor (€)<input data-global-field="marketValue" type="number" min="0" value="${numericPrice(player.marketValue)}"></label><label>Cláusula (€)<input data-global-field="clause" type="number" min="0" value="${numericPrice(player.clause)}"></label><label>Destino<select data-player-destination>${playerClubOptions(player.clubId)}</select></label><label>Precio operación (€)<input data-player-price type="number" min="0" value="${player.clubId===null?numericPrice(player.marketValue):numericPrice(player.clause)}"></label><button type="button" class="player-assign" data-player-assign>APLICAR</button><button type="button" class="player-delete" data-player-delete>ELIMINAR</button></div>`}
function renderPlayersAdmin(){const box=document.getElementById("playersAdmin");if(!box)return;const free=data.players.filter(player=>player.clubId===null).length;box.innerHTML=`<div class="players-admin-summary"><strong>${data.players.length}</strong><span>jugadores registrados</span><strong>${free}</strong><span>agentes libres</span></div><div class="new-player-form"><label>Nombre<input id="newPlayerName" maxlength="40" placeholder="Nombre del jugador"></label><label>Posición<select id="newPlayerPosition">${["Portero","Defensa","Medio","Delantero"].map(pos=>`<option>${pos}</option>`).join("")}</select></label><label>Precio / valor (€)<input id="newPlayerValue" type="number" min="0"></label><label>Cláusula (€)<input id="newPlayerClause" type="number" min="0"></label><button type="button" id="createPlayer">＋ CREAR AGENTE LIBRE</button></div><div class="global-players-list">${[...data.players].sort((a,b)=>(a.clubId!==null)-(b.clubId!==null)||a.name.localeCompare(b.name)).map(playerAdminRow).join("")}</div>`}
function movePlayer(player,destination,price){const previous=player.clubId,today=new Date().toISOString().slice(0,10);if(destination===previous)return;if(destination!==null&&data.clubs[destination].players.length>=18)throw new Error(`${data.clubs[destination].name} ya tiene 18 jugadores.`);const active=currentStint(player);if(active)active.to=today;if(previous!==null){data.clubs[previous].transfers.push({player:player.name,type:"Vendido",price,date:today,counterparty:destination===null?"Agentes libres":data.clubs[destination].name});const record=data.clubs[previous].playerHistory.find(item=>playerKey(item.name)===playerKey(player.name)&&!item.exitDate);if(record)record.exitDate=today}if(destination!==null){data.clubs[destination].transfers.push({player:player.name,type:"Comprado",price,date:today,counterparty:previous===null?"Agentes libres":data.clubs[previous].name});player.stints.push({clubId:destination,from:today,to:"",points:0,price,type:previous===null?"Fichaje":"Traspaso"});player.transferCount=(Number(player.transferCount)||0)+1;player.totalPaid=(Number(player.totalPaid)||0)+price}player.clubId=destination;data.clubs.forEach((club,i)=>club.players=data.players.filter(item=>item.clubId===i))}
const FORMATIONS=["1-4-4-2","1-4-3-3","1-3-4-3","1-3-3-4","1-5-3-2","1-5-4-1","1-4-5-1","1-3-5-2"];
function formationSpots(formation){const lines=formation.split("-").slice(1).map(Number),xs=lines.length===2?[36,76]:[29,55,82],spots=[{x:8,y:50,pos:"gk"}];lines.forEach((count,line)=>{for(let p=0;p<count;p++)spots.push({x:xs[line],y:(p+1)*100/(count+1),pos:line===0?"df":line===lines.length-1?"fw":"mf"})});return spots}
function renderLineup(club,jornada){const lineup=club.lineups[jornada],formation=club.formations[jornada],spots=formationSpots(formation);const markings=`<div class="field-markings"><i class="penalty-box left"></i><i class="goal-box left"></i><i class="penalty-box right"></i><i class="goal-box right"></i><i class="center-dot"></i></div>`;document.getElementById("footballField").innerHTML=markings+lineup.map((player,i)=>{const spot=spots[i];return `<div class="lineup-player ${spot.pos}" style="--x:${spot.x}%;--y:${spot.y}%"><span class="player-token">${i+1}</span><strong>${esc(player.name||`Jugador ${i+1}`)}</strong><small>${Number(player.points)||0} PTS</small></div>`}).join("");document.getElementById("lineupFormation").textContent=formation;document.getElementById("lineupTotal").textContent=lineup.reduce((sum,p)=>sum+(Number(p.points)||0),0)}
function lineupPlayerOptions(club,selected){const names=club.players.map(player=>player.name.trim()).filter(Boolean);if(selected&&!names.some(name=>name.toLocaleLowerCase("es")===selected.toLocaleLowerCase("es")))names.push(selected);return `<option value="">Sin seleccionar</option>${names.map(name=>`<option value="${esc(name)}" ${name===selected?"selected":""}>${esc(name)}</option>`).join("")}`}
function lineupAdminRows(club,jornada){return club.lineups[jornada].map((player,p)=>`<div class="admin-lineup-player" data-lineup-player="${p}"><span>${p+1}</span><label>Jugador<select data-lineup-field="name">${lineupPlayerOptions(club,player.name)}</select></label><label>Puntos<input data-lineup-field="points" type="number" step="0.01" value="${Number(player.points)||0}"></label></div>`).join("")}
function lineupEditorMarkup(club,i){return `<details class="lineup-admin"><summary>Alineaciones por jornada</summary><p class="matchday-help">Selecciona 11 jugadores distintos de la plantilla. Solo ellos sumarán puntos; el resto contará 0.</p><div class="admin-lineup-toolbar"><label>Jornada<select data-lineup-select="${i}">${Array.from({length:38},(_,j)=>`<option value="${j}">Jornada ${j+1}</option>`).join("")}</select></label><label>Formación<select data-formation-select="${i}">${FORMATIONS.map(f=>`<option ${club.formations[0]===f?'selected':''}>${f}</option>`).join("")}</select></label></div><div class="admin-lineup-grid">${lineupAdminRows(club,0)}</div></details>`}
function numericPrice(value){if(typeof value==="number")return value;return Number(String(value||0).replace(/[^0-9,.-]/g,"").replace(",","."))||0}
function formatMoney(value){return new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(value)||0)}
function transferEditorRow(item={player:"",type:"Comprado",price:0}){return `<div class="transfer-editor-row" data-transfer-date="${esc(item.date||"")}" data-transfer-counterparty="${esc(item.counterparty||"")}"><label>Concepto / jugador<input data-transfer-field="player" value="${esc(item.player)}" maxlength="40"></label><label>Operación<select data-transfer-field="type">${["Comprado","Vendido","Ingreso","Gasto"].map(type=>`<option ${item.type===type?"selected":""}>${type}</option>`).join("")}</select></label><label class="transfer-price-input">Importe<input data-transfer-field="price" type="number" min="0" step="1" value="${numericPrice(item.price)}"></label><button class="transfer-remove" type="button">×</button></div>`}
function transfersEditorMarkup(club){return `<details class="transfers-admin"><summary>Tesorería · ${formatMoney(clubBalance(club))}</summary><div class="balance-admin"><label>Saldo inicial (€)<input data-initial-balance type="number" min="0" step="1" value="${Number(club.initialBalance)||100000000}"></label><p>Los fichajes y ventas se registran automáticamente al mover jugadores. Puedes añadir otros movimientos manuales.</p></div><div class="transfers-editor-list">${club.transfers.map(transferEditorRow).join("")}</div><button class="transfer-add" type="button">＋ AÑADIR OTRO MOVIMIENTO</button></details>`}
function renderTransfers(club){const items=club.transfers.filter(t=>t.player);document.getElementById("transfersList").innerHTML=items.map((item,i)=>`<tr><td class="transfer-number">${String(i+1).padStart(2,"0")}</td><td class="transfer-player">${esc(item.player)}${item.counterparty?`<small>${esc(item.counterparty)}</small>`:""}</td><td><span class="transfer-type ${item.type==="Vendido"||item.type==="Ingreso"?"sell":"buy"}">${esc(item.type)}</span></td><td class="transfer-price">${formatMoney(numericPrice(item.price))}</td></tr>`).join("");document.getElementById("transfersEmpty").hidden=items.length>0;document.querySelector(".transfers-table").hidden=items.length===0}
function matchdaysEditorMarkup(club){const block=(start,end,title)=>`<div class="admin-round"><span class="admin-round-title">${title}</span>${club.matchdays.slice(start,end).map((points,offset)=>{const j=start+offset;return `<label>Jornada ${j+1}<input data-matchday="${j}" type="number" min="0" step="0.01" value="${Number(points)||0}"></label>`}).join("")}</div>`;return `<details class="matchdays-editor" open><summary>Puntos por jornada</summary><p class="matchday-help">Introduce directamente la puntuación total del equipo en cada jornada.</p><div class="matchday-inputs">${block(0,19,"Apertura · J1–J19")}${block(19,38,"Clausura · J20–J38")}</div></details>`}
function historyEditorMarkup(club){return `<details class="history-editor"><summary>Fechas del histórico de jugadores</summary><p class="matchday-help">Los jugadores y sus puntos se incorporan automáticamente desde las plantillas y alineaciones. Aquí solo debes completar sus fechas de entrada y salida.</p><div class="history-editor-list">${club.playerHistory.map(player=>historyEditorRow(player)).join("")}</div></details>`}
function historyEditorRow(player={name:"",entryDate:"",exitDate:""}){return `<div class="history-editor-row"><strong>${esc(player.name)}</strong><label>Entrada<input data-history-field="entryDate" type="date" value="${esc(player.entryDate||"")}"></label><label>Salida<input data-history-field="exitDate" type="date" min="${esc(player.entryDate||"")}" value="${esc(player.exitDate||"")}"></label></div>`}
function historyDays(entryDate,exitDate){if(!entryDate)return null;const start=Date.parse(`${entryDate}T00:00:00Z`),end=exitDate?Date.parse(`${exitDate}T00:00:00Z`):Date.now();if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)return null;return Math.floor((end-start)/86400000)+1}
function historyDate(value,fallback){if(!value)return fallback;return new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`))}
function historyTotal(player){return player.matchdayPoints.some(points=>points!==null)?player.matchdayPoints.reduce((sum,points)=>sum+(points===null?0:Number(points)||0),0):Number(player.legacyPoints)||0}
function historyBreakdown(player){const entries=player.matchdayPoints.map((points,j)=>points===null?"":`<i>J${j+1} <b>${Number(points)||0}</b></i>`).filter(Boolean);return entries.length?`<span class="history-breakdown">${entries.join("")}</span>`:""}
function renderHistory(club){const direction=document.getElementById("historySort").value==="asc"?1:-1;const players=[...club.playerHistory].filter(p=>p.name).sort((a,b)=>(historyTotal(a)-historyTotal(b))*direction||a.name.localeCompare(b.name));document.getElementById("historyList").innerHTML=players.map((player,i)=>{const days=historyDays(player.entryDate,player.exitDate);return `<tr><td class="history-rank">${String(i+1).padStart(2,"0")}</td><td class="history-name">${esc(player.name)}${historyBreakdown(player)}</td><td class="history-points">${historyTotal(player)}<small>PTS</small></td><td class="history-date">${historyDate(player.entryDate,"—")}</td><td class="history-date">${historyDate(player.exitDate,"EN EL CLUB")}</td><td class="history-days">${days??"—"}${days===null?"":"<small>DÍAS</small>"}</td></tr>`}).join("");document.getElementById("historyEmpty").hidden=players.length>0;document.querySelector(".history-table").hidden=players.length===0}
function playerKey(name){return String(name||"").trim().toLocaleLowerCase("es")}
function retirePlayer(club,index){const player=club.players[index],name=player.name.trim();if(!name)return;syncClubHistory(club);const key=playerKey(name),today=new Date().toISOString().slice(0,10);let record=club.playerHistory.find(item=>playerKey(item.name)===key);if(!record){record={name,entryDate:"",exitDate:today,legacyPoints:Number(player.points)||0,matchdayPoints:Array(38).fill(null)};club.playerHistory.push(record)}else if(!record.exitDate)record.exitDate=today;club.lineups.forEach(lineup=>lineup.forEach(slot=>{if(playerKey(slot.name)===key&&(Number(slot.points)||0)===0)slot.name=""}));club.players[index]={name:"",position:"Medio",marketValue:"",clause:"",points:0}}
function syncClubHistory(club,dateOverrides=new Map()){
  const records=new Map(club.playerHistory.filter(player=>player.name).map(player=>[playerKey(player.name),{...player,matchdayPoints:Array(38).fill(null)}]));
  const ensure=name=>{const key=playerKey(name);if(!key)return null;if(!records.has(key))records.set(key,{name:String(name).trim(),entryDate:"",exitDate:"",legacyPoints:0,matchdayPoints:Array(38).fill(null)});return records.get(key)};
  club.players.forEach(player=>ensure(player.name));
  club.lineups.forEach((lineup,jornada)=>lineup.forEach(player=>{const record=ensure(player.name);if(record)record.matchdayPoints[jornada]=Number(player.points)||0}));
  dateOverrides.forEach((dates,key)=>{const record=records.get(key);if(record){record.entryDate=dates.entryDate;record.exitDate=dates.exitDate}});
  club.playerHistory=[...records.values()];
  club.players.forEach(player=>{const record=records.get(playerKey(player.name));player.points=record?historyTotal(record):0});
  club.players.forEach(player=>{const stint=currentStint(player);if(stint)stint.points=Number(player.points)||0});
  if(club.lineups.some(lineup=>lineup.some(player=>player.name))){
    club.matchdays=club.lineups.map(lineup=>lineup.reduce((sum,player)=>sum+(Number(player.points)||0),0));
    club.pointsApertura=club.matchdays.slice(0,19).reduce((sum,points)=>sum+points,0);
    club.pointsClausura=club.matchdays.slice(19,38).reduce((sum,points)=>sum+points,0);
    club.pointsGeneral=club.pointsApertura+club.pointsClausura;
  }
}
function validateLeagueData(){
  for(const club of data.clubs){
    if(club.matchdays.some(points=>!Number.isFinite(Number(points))||Number(points)<0))throw new Error(`${club.name}: las puntuaciones por jornada deben ser números positivos.`);
  }
}
function renderMatchdays(club){const values=club.matchdays.map(Number);document.getElementById("matchdaysTotal").textContent=values.reduce((sum,value)=>sum+value,0).toLocaleString("es-ES");const best=Math.max(...values),worst=Math.min(...values),bestIndex=values.indexOf(best),worstIndex=values.indexOf(worst);document.getElementById("bestMatchdayPoints").textContent=best;document.getElementById("worstMatchdayPoints").textContent=worst;document.getElementById("bestMatchdayLabel").textContent=`Jornada ${bestIndex+1}`;document.getElementById("worstMatchdayLabel").textContent=`Jornada ${worstIndex+1}`;const max=Math.max(10,...values);const roundedMax=Math.ceil(max/10)*10;document.getElementById("chartScale").innerHTML=`<span>${roundedMax}</span><span>${Math.round(roundedMax*.75)}</span><span>${Math.round(roundedMax*.5)}</span><span>${Math.round(roundedMax*.25)}</span><span>0</span>`;document.getElementById("matchdaysChart").innerHTML=values.map((points,j)=>`<div class="chart-column"><div class="chart-bar" style="height:${Math.max(0,points)/roundedMax*100}%" data-tooltip="J${j+1}: ${points} pts"></div><span class="chart-label">${j+1}</span></div>`).join("");const rows=(start,end)=>values.slice(start,end).map((points,offset)=>{const jornada=start+offset+1;return `<div class="round-row"><span class="round-number">JORNADA ${jornada}</span><strong class="round-score">${points}<small>PTS</small></strong></div>`}).join("");document.getElementById("aperturaMatchdays").innerHTML=rows(0,19);document.getElementById("clausuraMatchdays").innerHTML=rows(19,38)}
function leagueBonus(field,top,step){const order=data.clubs.map((club,index)=>({index,points:Number(club[field])||0})).sort((a,b)=>b.points-a.points||a.index-b.index);return Object.fromEntries(order.map((entry,pos)=>[entry.index,pos<3?top[pos]:Math.max(0,top[2]-step*(pos-2))]))}
function cupWins(index){return Object.values(data.cups).reduce((total,cup)=>total+CUP_STAGE_SPECS.reduce((sum,stage)=>sum+cup.stages[stage.key].filter(tie=>tie.winner===index).length,0),0)}
function rankingRows(){const ap=leagueBonus("pointsApertura",[600,400,300],25),cl=leagueBonus("pointsClausura",[600,400,300],25),rf=leagueBonus("pointsGeneral",[1200,800,600],50),done=data.leaguesCompleted;return data.clubs.map((club,index)=>{const participation=(Number(club.pointsApertura)||0)+(Number(club.pointsClausura)||0)+(Number(club.pointsGeneral)||0),league=(done.apertura?ap[index]:0)+(done.clausura?cl[index]:0)+(done.general?rf[index]:0),cups=cupWins(index)*50;return {club,index,participation,league,cups,total:participation+league+cups}}).sort((a,b)=>b.total-a.total||a.index-b.index)}
function renderRanking(){document.getElementById("rankingRfList").innerHTML=rankingRows().map((row,pos)=>`<a class="ranking-row" href="#club/${row.index}" data-club="${row.index}"><div class="ranking-club"><b>${String(pos+1).padStart(2,"0")}</b>${crestMarkup(row.club,row.index,"mini-crest")}<span><strong>${esc(row.club.name)}</strong><small>${esc(row.club.manager)}</small></span></div><span>${row.participation}<small>PR</small></span><span>${row.league}<small>PR</small></span><span>${row.cups}<small>PR</small></span><strong>${row.total}<small>PR</small></strong></a>`).join("")}
const TITLE_BADGE_IMAGES=["liga_apertura","liga_clausura","liga_ronda_final","copa_apertura","copa_clausura"];
function titleBadgeMarkup(name,count,index){const stars=Array.from({length:10},(_,i)=>`<i class="${i<count?'won':''}">★</i>`).join("");return `<div class="title-badge title-badge-${index}"><div class="title-stars">${stars}</div><img class="title-medal-image" src="imagenes/insignias_torneos/${TITLE_BADGE_IMAGES[index]}.png" alt="Insignia de ${esc(name)}"><strong>${esc(name)}</strong><small>${count} ${count===1?'TÍTULO':'TÍTULOS'}</small></div>`}
function teamOption(value,selected,label="Seleccionar equipo"){return `<option value="${value??''}" ${String(selected??'')===String(value??'')?'selected':''}>${esc(label)}</option>`}
function clubOptions(selected){return teamOption(null,selected)+data.clubs.map((club,i)=>teamOption(i,selected,club.name)).join("")}
function cupTieEditor(tie,stageKey,index){return `<div class="cup-tie-editor" data-stage="${stageKey}" data-tie="${index}"><strong>ELIMINATORIA ${index+1}</strong><label>Fecha / jornada<input data-cup-field="date" value="${esc(tie.date)}" placeholder="Pendiente"></label>${[0,1].map(team=>`<div class="cup-editor-team"><label>Equipo ${team+1}<select data-cup-team="${team}">${clubOptions(tie.teams[team])}</select></label><label>Ida<input data-cup-score="0:${team}" type="number" min="0" value="${tie.scores[0][team]??''}"></label><label>Vuelta<input data-cup-score="1:${team}" type="number" min="0" value="${tie.scores[1][team]??''}"></label></div>`).join("")}<label>Clasificado<select data-cup-field="winner">${clubOptions(tie.winner)}</select></label></div>`}
function renderCupAdmin(){document.getElementById("cupAdminEditors").innerHTML=Object.entries(data.cups).map(([key,cup])=>`<details class="cup-admin" data-cup-admin="${key}"><summary>Copa ${key==='apertura'?'Apertura':'Clausura'}</summary><div class="cup-special-editor">${cup.bestLosers.map((team,i)=>`<label>Mejor perdedor ${i+1}<select data-cup-loser="${i}">${clubOptions(team)}</select></label>`).join("")}</div>${CUP_STAGE_SPECS.map(stage=>`<section><h4>${stage.title}</h4><div class="cup-admin-grid">${cup.stages[stage.key].map((tie,i)=>cupTieEditor(tie,stage.key,i)).join("")}</div></section>`).join("")}</details>`).join("")}
function renderFaq(){const list=data.faqs.filter(item=>item.question.trim());document.getElementById("faqList").innerHTML=list.map((item,i)=>`<details class="faq-item"><summary><span>${String(i+1).padStart(2,"0")}</span><strong>${esc(item.question)}</strong><i>＋</i></summary><div class="faq-answer">${esc(item.answer).replace(/\n/g,"<br>")}</div></details>`).join("");document.getElementById("faqEmpty").hidden=list.length>0}
function faqAdminRow(item,index){return `<article class="faq-admin-row" data-faq-id="${esc(item.id)}"><span class="faq-admin-number">${String(index+1).padStart(2,"0")}</span><label>Pregunta<input data-faq-field="question" value="${esc(item.question)}" maxlength="180" placeholder="Escribe la pregunta"></label><label>Respuesta o explicación<textarea data-faq-field="answer" rows="5" maxlength="3000" placeholder="Escribe la respuesta completa">${esc(item.answer)}</textarea></label><div class="faq-admin-actions"><button type="button" data-faq-up aria-label="Subir pregunta">↑</button><button type="button" data-faq-down aria-label="Bajar pregunta">↓</button><button type="button" data-faq-delete>ELIMINAR</button></div></article>`}
function renderFaqAdmin(){document.getElementById("faqAdmin").innerHTML=`<div class="faq-admin-toolbar"><strong>${data.faqs.length}</strong><span>preguntas</span><button type="button" id="faqAdd">＋ AÑADIR PREGUNTA</button><button type="button" id="faqPublish">PUBLICAR FAQ</button></div><p class="faq-publish-help">Después de escribir o editar las preguntas, pulsa «Publicar FAQ» para guardarlas y mostrarlas en la web.</p><div class="faq-admin-list">${data.faqs.map(faqAdminRow).join("")}</div>`}
let adminActive=false;
function secureShuffle(items){const result=[...items];for(let i=result.length-1;i>0;i--){const range=0x100000000-(0x100000000%(i+1));let value;do value=crypto.getRandomValues(new Uint32Array(1))[0];while(value>=range);const j=value%(i+1);[result[i],result[j]]=[result[j],result[i]]}return result}
function authorizeDraw(){const password=prompt("Contraseña del sorteo:");if(password===null)return false;if(password!=="sorteo"){alert("Contraseña incorrecta.");return false}return true}
function renderDraw(){document.getElementById("drawNav").hidden=!data.draw.enabled;document.getElementById("sorteos").hidden=!data.draw.enabled;document.getElementById("drawTitle").textContent=data.draw.title;const selection=Array.isArray(data.draw.selection)?data.draw.selection:(data.draw.pairs.length?data.draw.participants:data.clubs.map((_,i)=>i));document.getElementById("drawTeams").innerHTML=data.clubs.map((club,i)=>`<label><input type="checkbox" value="${i}" ${selection.includes(i)?"checked":""}><span>${crestMarkup(club,i,"draw-team-crest")}<strong>${esc(club.name)}</strong></span></label>`).join("");updateDrawSelectionCount();document.getElementById("drawPairs").innerHTML=data.draw.pairs.length?data.draw.pairs.map((pair,i)=>`<article style="--delay:${i*.12}s"><small>ENFRENTAMIENTO ${String(i+1).padStart(2,"0")}</small><div>${esc(data.clubs[pair[0]]?.name||"")}</div><b>VS</b><div>${esc(data.clubs[pair[1]]?.name||"")}</div></article>`).join(""):`<p class="draw-empty">El bombo está preparado. El resultado aparecerá aquí.</p>`;document.getElementById("drawTimestamp").textContent=data.draw.timestamp?`Sorteo realizado: ${new Date(data.draw.timestamp).toLocaleString("es-ES")}`:""}
function updateDrawSelectionCount(){const count=document.querySelectorAll("#drawTeams input:checked").length,total=data.clubs.length,box=document.getElementById("drawSelectionCount");if(box)box.textContent=`${count} de ${total} equipos seleccionados${count%2?" · debe ser un número par":""}`}
function render(){
  document.getElementById("brandName").textContent=data.league;
  document.getElementById("seasonText").textContent=data.season;
  document.getElementById("welcomeText").textContent=data.welcome;
  document.title=data.league;
  document.getElementById("teamsGrid").innerHTML=data.clubs.map((club,i)=>`<a class="team-card" href="#club/${i}" data-club="${i}"><span class="team-number">${String(i+1).padStart(2,"0")}</span>${crestMarkup(club,i)}<h3>${esc(club.name)}</h3><div class="card-manager"><span>MANAGER</span><strong>${esc(club.manager)}</strong></div><span class="team-arrow">→</span></a>`).join("");
  document.getElementById("aperturaList").innerHTML=standingsMarkup("pointsApertura");
  document.getElementById("clausuraList").innerHTML=standingsMarkup("pointsClausura");
  document.getElementById("generalList").innerHTML=standingsMarkup("pointsGeneral");
  renderLeagueMatchday("apertura",document.getElementById("aperturaMatchdaySelect").value||0);
  renderLeagueMatchday("clausura",document.getElementById("clausuraMatchdaySelect").value||19);
  renderCupFormats();
  renderRanking();
  renderTeamEditors();
  renderCupAdmin();
  renderFaq();
  renderFaqAdmin();
  renderBadgeLibraries();
  renderDraw();
}
const BADGE_PRESETS={fundador:{name:"Equipo Fundador",image:"imagenes/insignias/equipo_fundador_512.png"},mejor:{name:"Mejor Jornada",image:"imagenes/insignias/mejor_jornada_512.png"},peor:{name:"Peor Jornada",image:"imagenes/insignias/peor_jornada_512.png"}};
function renderBadgeLibraries(){document.querySelectorAll(".badge-editor").forEach(details=>{const i=Number(details.dataset.clubIndex),buttons=Object.entries(BADGE_PRESETS).map(([key,badge])=>`<button class="badge-preset" type="button" data-badge-preset="${key}" data-club="${i}"><img src="${badge.image}" alt="">${badge.name}</button>`).join("");const library=`<div class="badge-library"><small>INSIGNIAS DISPONIBLES</small>${buttons}</div>`;details.querySelector("summary").insertAdjacentHTML("afterend",library);details.querySelectorAll(".badge-field").forEach((field,b)=>{const badge=data.clubs[i].badges[b];if(badge.name||badge.image)field.insertAdjacentHTML("beforeend",`<button class="badge-remove" type="button" data-badge-remove="${i}:${b}">× ELIMINAR INSIGNIA</button>`)})})}
function renderTeamEditors(){
  const club=data.clubs[adminClubIndex],i=adminClubIndex;
  document.getElementById("adminClubSelect").innerHTML=data.clubs.map((item,index)=>`<option value="${index}" ${index===i?"selected":""}>${esc(item.name)} · ${esc(item.manager)}</option>`).join("");
  document.getElementById("teamInputs").innerHTML=`<div class="team-editor" data-editor="${i}"><span class="team-editor-title">CLUB ${String(i+1).padStart(2,"0")}</span>${club.crest?`<img class="upload-preview" src="${esc(club.crest)}" alt="">`:""}<label>Nombre<input data-field="name" value="${esc(club.name)}" maxlength="32"></label><label>Manager<input data-field="manager" value="${esc(club.manager)}" maxlength="40"></label>${matchdaysEditorMarkup(club)}<details class="title-wins-editor"><summary>Títulos e insignias oficiales</summary>${COMPETITION_NAMES.map((name,t)=>`<label>${name}<input data-title-win="${t}" type="number" min="0" max="10" value="${club.titleWins[t]}"></label>`).join("")}</details><label>Escudo 512 × 512<input data-crest-input="${i}" type="file" accept="image/png,image/jpeg,image/webp"></label><p class="upload-help">PNG, JPG o WebP. Recomendado: 512 × 512 y menos de 1 MB.</p><details class="badge-editor" data-club-index="${i}"><summary>Otras insignias del club</summary>${club.badges.map((badge,b)=>`<div class="badge-field">${badge.image?`<img src="${esc(badge.image)}" alt="">`:""}<label>Insignia ${b+1}<input data-badge-name="${b}" value="${esc(badge.name)}" placeholder="Ej: Equipo Fundador" maxlength="32"></label><label>Icono<input data-badge-input="${i}:${b}" type="file" accept="image/png,image/jpeg,image/webp"></label></div>`).join("")}</details></div>`;
  document.querySelectorAll("[data-editor]").forEach(editor=>{const index=Number(editor.dataset.editor),club=data.clubs[index],managerLabel=editor.querySelector('[data-field="manager"]').closest("label"),crestLabel=editor.querySelector("[data-crest-input]").closest("label");managerLabel.insertAdjacentHTML("afterend",`<label>Lema del equipo<input data-field="motto" value="${esc(club.motto||'')}" maxlength="120"></label>`);crestLabel.insertAdjacentHTML("afterend",`${club.kit?`<img class="kit-upload-preview" src="${esc(club.kit)}" alt="Equipación">`:""}<label>Equipación 512 × 512<input data-kit-input="${index}" type="file" accept="image/png,image/jpeg,image/webp"></label>`)});
}
function captureVisibleClubDraft(){const editor=document.querySelector("#teamInputs [data-editor]");if(!editor)return;const index=Number(editor.dataset.editor),club=data.clubs[index];club.name=editor.querySelector('[data-field="name"]').value.trim()||`Equipo ${index+1}`;club.manager=editor.querySelector('[data-field="manager"]').value.trim()||"Por asignar";club.motto=editor.querySelector('[data-field="motto"]').value.trim();editor.querySelectorAll("[data-matchday]").forEach(input=>club.matchdays[Number(input.dataset.matchday)]=Math.max(0,Number(input.value)||0));club.pointsApertura=club.matchdays.slice(0,19).reduce((sum,points)=>sum+Number(points||0),0);club.pointsClausura=club.matchdays.slice(19,38).reduce((sum,points)=>sum+Number(points||0),0);club.pointsGeneral=club.pointsApertura+club.pointsClausura;editor.querySelectorAll("[data-badge-name]").forEach(input=>club.badges[Number(input.dataset.badgeName)].name=input.value.trim());editor.querySelectorAll("[data-title-win]").forEach(input=>club.titleWins[Number(input.dataset.titleWin)]=Math.max(0,Math.min(10,Number(input.value)||0)))}
function navigate(route){
  document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));
  const isClub=route.startsWith("club/");
  const target=isClub?"club":(["inicio","equipos","apertura","clausura","liga-general","copa-apertura","copa-clausura","ranking-rf","normativa","faq","sorteos"].includes(route)&&!(route==="sorteos"&&!data.draw.enabled)?route:"inicio");
  document.getElementById(target).classList.add("active");
  document.querySelectorAll(".nav a").forEach(a=>a.classList.toggle("active",a.dataset.route===target));
  if(isClub){
    const index=Number(route.split("/")[1]);const club=data.clubs[index];
    if(club){currentClubIndex=index;
      document.getElementById("clubName").textContent=club.name;
      document.getElementById("clubManager").textContent=club.manager;
      document.getElementById("clubMotto").textContent=club.motto||"La historia está a punto de escribirse.";
      const kitImage=document.getElementById("clubKitImage"),crestImage=document.getElementById("clubDisplayCrest");kitImage.src=club.kit||"";kitImage.hidden=!club.kit;kitImage.nextElementSibling.hidden=Boolean(club.kit);crestImage.src=club.crest||"";crestImage.hidden=!club.crest;crestImage.nextElementSibling.hidden=Boolean(club.crest);
      renderMatchdays(club);
      const activeBadges=club.badges.filter(b=>b.name||b.image);document.getElementById("clubBadges").innerHTML=`<div class="official-title-badges">${COMPETITION_NAMES.map((name,t)=>titleBadgeMarkup(name,club.titleWins[t],t)).join("")}</div>${activeBadges.map(b=>`<div class="club-badge">${b.image?`<img src="${esc(b.image)}" alt="${esc(b.name||'Insignia')}">`:`<span class="badge-placeholder">★</span>`}<strong>${esc(b.name||"Insignia")}</strong></div>`).join("")}`;
      const crest=document.getElementById("clubCrest");crest.textContent=club.crest?"":initials(club.name,index);crest.classList.toggle("has-image",Boolean(club.crest));crest.style.backgroundImage=club.crest?`url("${club.crest}")`:"";crest.style.backgroundSize="contain";crest.style.backgroundPosition="center";crest.style.backgroundRepeat="no-repeat";
    }
  }
  document.getElementById("mainNav").classList.remove("open");window.scrollTo(0,0);
}
document.addEventListener("click",e=>{const route=e.target.closest("[data-route]");if(route){e.preventDefault();location.hash=route.dataset.route}const club=e.target.closest("[data-club]");if(club){e.preventDefault();location.hash=`club/${club.dataset.club}`}});
document.addEventListener("click",e=>{const jump=e.target.closest("[data-help-target]");if(!jump)return;e.preventDefault();document.getElementById(jump.dataset.helpTarget)?.scrollIntoView({behavior:"smooth",block:"start"})});
window.addEventListener("hashchange",()=>navigate(location.hash.slice(1)||"inicio"));
document.getElementById("aperturaMatchdaySelect").addEventListener("change",e=>renderLeagueMatchday("apertura",e.target.value));
document.getElementById("clausuraMatchdaySelect").addEventListener("change",e=>renderLeagueMatchday("clausura",e.target.value));
document.getElementById("menuToggle").addEventListener("click",()=>document.getElementById("mainNav").classList.toggle("open"));

const modal=document.getElementById("adminModal");
function openModal(){modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.getElementById("password").focus()}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.getElementById("loginError").textContent=""}
function enterAdmin(){
  adminActive=true;
  document.getElementById("loginView").hidden=true;document.getElementById("editorView").hidden=false;
  document.getElementById("editLeague").value=data.league;document.getElementById("editSeason").value=data.season;document.getElementById("editWelcome").value=data.welcome;document.getElementById("completedApertura").checked=data.leaguesCompleted.apertura;document.getElementById("completedClausura").checked=data.leaguesCompleted.clausura;document.getElementById("completedGeneral").checked=data.leaguesCompleted.general;document.getElementById("drawEnabled").checked=data.draw.enabled;document.getElementById("drawAdminTitle").value=data.draw.title;renderTeamEditors();renderBadgeLibraries();renderDraw();
}
window.enterAdmin=enterAdmin;
document.getElementById("adminOpen").addEventListener("click",openModal);
document.getElementById("adminClose").addEventListener("click",closeModal);
modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
document.querySelector(".admin-module-nav").addEventListener("click",e=>{const button=e.target.closest("[data-admin-module]");if(!button)return;document.querySelectorAll("[data-admin-module]").forEach(item=>item.classList.toggle("active",item===button));document.querySelectorAll("[data-admin-panel]").forEach(panel=>panel.classList.toggle("active",panel.dataset.adminPanel===button.dataset.adminModule));document.querySelector(".modal-card").scrollTop=0});
document.getElementById("adminClubSelect").addEventListener("change",e=>{captureVisibleClubDraft();adminClubIndex=Number(e.target.value);renderTeamEditors();renderBadgeLibraries()});
document.getElementById("loginForm").addEventListener("submit",async e=>{
  e.preventDefault();const password=document.getElementById("password").value,errorBox=document.getElementById("loginError");
  if(window.remoteEnabled){try{await remoteLogin(password)}catch(error){errorBox.textContent=error.message||"No se pudo iniciar sesión.";return}}
  else{const saved=localStorage.getItem(PASSWORD_KEY)||"cambiar-esta-clave";if(password!==saved){errorBox.textContent="Contraseña incorrecta.";return}}
  enterAdmin();
});
document.getElementById("teamInputs").addEventListener("change",async e=>{
  const input=e.target.closest("[data-crest-input],[data-badge-input]");if(!input||!input.files[0])return;
  const file=input.files[0];
  if(file.size>1500000){alert("El archivo es demasiado grande. Usa una imagen de menos de 1,5 MB.");input.value="";return}
  if(window.remoteEnabled){try{const isCrest=input.hasAttribute("data-crest-input"),assetUrl=await uploadLeagueAsset(file,isCrest?"escudos":"insignias");if(isCrest){data.clubs[Number(input.dataset.crestInput)].crest=assetUrl;const old=input.closest(".team-editor").querySelector(".upload-preview");if(old)old.remove();const preview=document.createElement("img");preview.className="upload-preview";preview.src=assetUrl;input.closest(".team-editor").prepend(preview)}else{const [clubIndex,badgeIndex]=input.dataset.badgeInput.split(":").map(Number);data.clubs[clubIndex].badges[badgeIndex].image=assetUrl;const field=input.closest(".badge-field"),old=field.querySelector("img");if(old)old.remove();const preview=document.createElement("img");preview.src=assetUrl;field.prepend(preview)}return}catch(error){alert(`No se pudo subir la imagen: ${error.message}`);return}}
  const image=new Image();const reader=new FileReader();
  reader.onload=()=>{image.onload=()=>{if(input.hasAttribute("data-crest-input")){if(image.width!==512||image.height!==512){alert(`El escudo mide ${image.width} × ${image.height}. Se recomienda 512 × 512, aunque puedes guardarlo igualmente.`)}data.clubs[Number(input.dataset.crestInput)].crest=reader.result;const old=input.closest(".team-editor").querySelector(".upload-preview");if(old)old.remove();const preview=document.createElement("img");preview.className="upload-preview";preview.src=reader.result;input.closest(".team-editor").prepend(preview)}else{const [clubIndex,badgeIndex]=input.dataset.badgeInput.split(":").map(Number);data.clubs[clubIndex].badges[badgeIndex].image=reader.result;const field=input.closest(".badge-field");const old=field.querySelector("img");if(old)old.remove();const preview=document.createElement("img");preview.src=reader.result;field.prepend(preview)}};image.src=reader.result};reader.readAsDataURL(file);
});
document.getElementById("teamInputs").addEventListener("change",e=>{const input=e.target.closest("[data-kit-input]");if(!input||!input.files[0])return;const file=input.files[0],editor=input.closest("[data-editor]"),index=Number(input.dataset.kitInput),image=new Image(),reader=new FileReader();if(file.size>1500000){alert("La imagen es demasiado grande. Usa un archivo de menos de 1,5 MB.");input.value="";return}reader.onload=()=>{image.onload=async()=>{if(image.width!==512||image.height!==512){alert(`La equipación mide ${image.width} × ${image.height}. Debe medir exactamente 512 × 512 píxeles.`);input.value="";return}try{const src=window.remoteEnabled?await uploadLeagueAsset(file,"equipaciones"):reader.result;data.clubs[index].kit=src;editor.querySelector(".kit-upload-preview")?.remove();const preview=document.createElement("img");preview.className="kit-upload-preview";preview.src=src;input.closest("label").before(preview)}catch(error){alert(`No se pudo subir la equipación: ${error.message}`)}};image.src=reader.result};reader.readAsDataURL(file)});
document.getElementById("teamInputs").addEventListener("click",e=>{const preset=e.target.closest("[data-badge-preset]");if(!preset)return;const club=data.clubs[Number(preset.dataset.club)],badge=club.badges.find(b=>!b.name&&!b.image),selected=BADGE_PRESETS[preset.dataset.badgePreset];if(!badge){alert("Este club ya tiene ocupadas sus cuatro insignias.");return}badge.name=selected.name;badge.image=selected.image;renderTeamEditors();renderBadgeLibraries()});
document.getElementById("teamInputs").addEventListener("click",e=>{const remove=e.target.closest("[data-badge-remove]");if(!remove)return;const [clubIndex,badgeIndex]=remove.dataset.badgeRemove.split(":").map(Number),field=remove.closest(".badge-field");data.clubs[clubIndex].badges[badgeIndex]={name:"",image:""};field.querySelector("[data-badge-name]").value="";field.querySelector("img")?.remove();field.querySelector("input[type=file]").value="";remove.remove()});
document.getElementById("faqAdmin").addEventListener("input",e=>{const row=e.target.closest("[data-faq-id]"),field=e.target.closest("[data-faq-field]");if(!row||!field)return;const item=data.faqs.find(faq=>faq.id===row.dataset.faqId);if(item)item[field.dataset.faqField]=field.value});
document.getElementById("faqAdmin").addEventListener("click",e=>{
  if(e.target.id==="faqAdd"){data.faqs.push({id:crypto.randomUUID(),question:"",answer:""});renderFaqAdmin();const rows=document.querySelectorAll(".faq-admin-row"),count=rows.length;if(count)rows[count-1].querySelector('[data-faq-field="question"]').focus();return}
  if(e.target.id==="faqPublish"){renderFaq();document.querySelector(".admin-save-bar [type=submit]").click();return}
  const row=e.target.closest("[data-faq-id]");if(!row)return;const index=data.faqs.findIndex(item=>item.id===row.dataset.faqId);if(index<0)return;
  if(e.target.closest("[data-faq-delete]")){if(confirm("¿Eliminar esta pregunta frecuente?")){data.faqs.splice(index,1);renderFaqAdmin()}return}
  if(e.target.closest("[data-faq-up]")&&index>0)[data.faqs[index-1],data.faqs[index]]=[data.faqs[index],data.faqs[index-1]];
  else if(e.target.closest("[data-faq-down]")&&index<data.faqs.length-1)[data.faqs[index+1],data.faqs[index]]=[data.faqs[index],data.faqs[index+1]];
  else return;
  renderFaqAdmin();
});
function optionalIndex(value){return value===""?null:Number(value)}
function readCupEditors(){document.querySelectorAll("[data-cup-admin]").forEach(editor=>{const cup=data.cups[editor.dataset.cupAdmin];editor.querySelectorAll("[data-cup-loser]").forEach(select=>cup.bestLosers[Number(select.dataset.cupLoser)]=optionalIndex(select.value));editor.querySelectorAll(".cup-tie-editor").forEach(row=>{const tie=cup.stages[row.dataset.stage][Number(row.dataset.tie)];row.querySelectorAll("[data-cup-team]").forEach(select=>tie.teams[Number(select.dataset.cupTeam)]=optionalIndex(select.value));row.querySelectorAll("[data-cup-score]").forEach(input=>{const [leg,team]=input.dataset.cupScore.split(":").map(Number);tie.scores[leg][team]=input.value===""?null:Math.max(0,Number(input.value)||0)});tie.date=row.querySelector('[data-cup-field="date"]').value.trim();tie.winner=optionalIndex(row.querySelector('[data-cup-field="winner"]').value)})})}
document.getElementById("editorForm").addEventListener("submit",async e=>{
  e.preventDefault();data.league=document.getElementById("editLeague").value.trim()||DEFAULT_DATA.league;data.season=document.getElementById("editSeason").value.trim()||DEFAULT_DATA.season;data.welcome=document.getElementById("editWelcome").value.trim()||DEFAULT_DATA.welcome;data.leaguesCompleted={apertura:document.getElementById("completedApertura").checked,clausura:document.getElementById("completedClausura").checked,general:document.getElementById("completedGeneral").checked};data.draw.enabled=document.getElementById("drawEnabled").checked;data.draw.title=document.getElementById("drawAdminTitle").value.trim()||"Sorteo oficial";
  document.querySelectorAll("[data-editor]").forEach(editor=>{const index=Number(editor.dataset.editor),club=data.clubs[index];club.name=editor.querySelector('[data-field="name"]').value.trim()||`Equipo ${index+1}`;club.manager=editor.querySelector('[data-field="manager"]').value.trim()||"Por asignar";club.motto=editor.querySelector('[data-field="motto"]').value.trim();editor.querySelectorAll("[data-matchday]").forEach(input=>club.matchdays[Number(input.dataset.matchday)]=Math.max(0,Number(input.value)||0));club.pointsApertura=club.matchdays.slice(0,19).reduce((sum,points)=>sum+Number(points||0),0);club.pointsClausura=club.matchdays.slice(19,38).reduce((sum,points)=>sum+Number(points||0),0);club.pointsGeneral=club.pointsApertura+club.pointsClausura;editor.querySelectorAll("[data-badge-name]").forEach(input=>club.badges[Number(input.dataset.badgeName)].name=input.value.trim());editor.querySelectorAll("[data-title-win]").forEach(input=>club.titleWins[Number(input.dataset.titleWin)]=Math.max(0,Math.min(10,Number(input.value)||0)))});
  readCupEditors();const saveButton=e.submitter||e.currentTarget.querySelector('[type="submit"]'),message=document.getElementById("saveMessage");
  try{validateLeagueData();saveButton.disabled=true;saveButton.textContent="GUARDANDO…";message.textContent="Comprobando y publicando los cambios…";localStorage.setItem(STORAGE_KEY,JSON.stringify(data));if(window.remoteEnabled)await remoteSave();render();message.textContent="Cambios guardados online correctamente."}catch(error){message.textContent=`No se pudo guardar: ${error.message||"error desconocido"}`}finally{saveButton.disabled=false;saveButton.textContent="GUARDAR CAMBIOS"}setTimeout(()=>message.textContent="",7000);
});
document.getElementById("drawTeams").addEventListener("change",()=>{data.draw.selection=[...document.querySelectorAll("#drawTeams input:checked")].map(input=>Number(input.value));localStorage.setItem(STORAGE_KEY,JSON.stringify(data));updateDrawSelectionCount()});
document.querySelector(".draw-selection-tools").addEventListener("click",e=>{const action=e.target.dataset.drawSelection;if(!action)return;document.querySelectorAll("#drawTeams input").forEach(input=>input.checked=action==="all");document.getElementById("drawTeams").dispatchEvent(new Event("change"))});
document.getElementById("drawButton").addEventListener("click",async()=>{if(!authorizeDraw())return;const selected=[...document.querySelectorAll("#drawTeams input:checked")].map(input=>Number(input.value));if(selected.length<2||selected.length%2){alert("Selecciona un número par de equipos, con un mínimo de dos.");return}const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),button=document.getElementById("drawButton"),theater=document.getElementById("drawTheater"),status=document.getElementById("drawStatus"),progress=document.getElementById("drawProgress"),liveA=document.getElementById("drawLiveA"),liveB=document.getElementById("drawLiveB"),pairsBox=document.getElementById("drawPairs"),shuffled=secureShuffle(selected),pairs=Array.from({length:shuffled.length/2},(_,i)=>[shuffled[i*2],shuffled[i*2+1]]),extract=async(target,team,number,total)=>{status.textContent=`EXTRAYENDO EQUIPO ${number} DE ${total}`;progress.style.transition="none";progress.style.width="0";await wait(50);progress.style.transition="width 18s linear";progress.style.width="100%";const spin=setInterval(()=>target.textContent=data.clubs[selected[Math.floor(Math.random()*selected.length)]].name,90);await wait(18000);clearInterval(spin);target.textContent=data.clubs[team].name;theater.classList.add("pair-locked");await wait(2000);theater.classList.remove("pair-locked")};button.disabled=true;button.textContent="SORTEO EN DIRECTO…";document.querySelector(".draw-result").classList.add("drawing");theater.hidden=false;pairsBox.innerHTML="";document.getElementById("drawTimestamp").textContent="";for(let count=3;count>0;count--){status.textContent=`EL BOMBO SE ABRE EN ${count}`;await wait(800)}let extracted=0;for(let i=0;i<pairs.length;i++){liveA.textContent="?";liveB.textContent="?";await extract(liveA,pairs[i][0],++extracted,selected.length);await extract(liveB,pairs[i][1],++extracted,selected.length);pairsBox.insertAdjacentHTML("beforeend",`<article class="just-drawn"><small>ENFRENTAMIENTO ${String(i+1).padStart(2,"0")}</small><div>${esc(data.clubs[pairs[i][0]].name)}</div><b>VS</b><div>${esc(data.clubs[pairs[i][1]].name)}</div></article>`);await wait(1000)}status.textContent="SORTEO COMPLETADO";await wait(1200);data.draw.participants=selected;data.draw.pairs=pairs;data.draw.timestamp=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));if(window.remoteEnabled)try{await remoteSave()}catch(error){alert(`El sorteo se ha realizado, pero no se pudo publicar: ${error.message}`)}theater.hidden=true;document.querySelector(".draw-result").classList.remove("drawing");renderDraw();button.disabled=false;button.textContent="REALIZAR SORTEO"});
document.getElementById("drawReset").addEventListener("click",async()=>{if(!authorizeDraw()||!confirm("¿Reiniciar el sorteo y borrar todos los enfrentamientos publicados?"))return;data.draw.participants=[];data.draw.pairs=[];data.draw.timestamp="";data.draw.resetToken=DEFAULT_DATA.draw.resetToken;localStorage.setItem(STORAGE_KEY,JSON.stringify(data));if(window.remoteEnabled)try{await remoteSave()}catch(error){alert(`Se ha reiniciado en este dispositivo, pero no se pudo publicar: ${error.message}`)}renderDraw()});
document.getElementById("changePassword").addEventListener("click",async()=>{const next=prompt("Escribe tu nueva contraseña (mínimo 8 caracteres):");if(next&&next.length>=8){try{if(window.remoteEnabled)await remoteChangePassword(next);else localStorage.setItem(PASSWORD_KEY,next);alert("Contraseña actualizada correctamente.")}catch(error){alert(`No se pudo cambiar: ${error.message}`)}}else if(next!==null){alert("La contraseña debe tener al menos 8 caracteres.")}});
render();navigate(location.hash.slice(1)||"inicio");
