const DEFAULT_CRESTS=[
  "imagenes/escudos_equipos/atletico_lesterol_512x512.png",
  "imagenes/escudos_equipos/aubameyang_y_10_mas_transparent_512x512.png",
  "imagenes/escudos_equipos/mariscos_recio_transparent_512x512.png",
  "imagenes/escudos_equipos/maccabi_de_levantar_transparent_512x512.png",
  "imagenes/escudos_equipos/recreativo_de_juerga_transparent_512x512.png",
  "imagenes/escudos_equipos/renacidos_cf_transparent_512x512.png",
  "imagenes/escudos_equipos/sporting_de_finidi_transparent_v2_512x512.png",
  "imagenes/escudos_equipos/moleiros_team_transparent_512x512.png",
  "imagenes/escudos_equipos/los_pridecines_transparent_v5_512x512.png",
  "imagenes/escudos_equipos/ozempic_de_leon_transparent_512x512.png",
  "imagenes/escudos_equipos/equipo_11_transparent_512x512.png",
  "imagenes/escudos_equipos/aston_birra_transparent_512x512.png"
];
const DEFAULT_CLUBS=Array.from({length:12},(_,i)=>({
  name:i===0?"Atlético Lesterol":`Equipo ${i+1}`,
  manager:"Por asignar",
  points:0,
  pointsApertura:0,
  pointsClausura:0,
  pointsGeneral:0,
  crest:DEFAULT_CRESTS[i],
  badges:Array.from({length:4},()=>({name:"",image:""})),
  players:Array.from({length:25},()=>({name:"",position:"Medio",marketValue:"",clause:"",points:0})),
  matchdays:Array.from({length:38},()=>0),
  playerHistory:[],
  lineups:Array.from({length:38},()=>Array.from({length:11},()=>({name:"",points:0}))),
  formations:Array.from({length:38},()=>"1-4-3-3"),
  transfers:[],
  initialBalance:0,
  titleWins:Array(5).fill(0)
}));
const CUP_STAGE_SPECS=[{key:"preliminary",title:"RONDA PREVIA",count:6,prefix:"ELIMINATORIA"},{key:"quarterfinals",title:"CUARTOS DE FINAL",count:4,prefix:"CUARTO"},{key:"semifinals",title:"SEMIFINALES",count:2,prefix:"SEMIFINAL"},{key:"final",title:"FINAL",count:1,prefix:"GRAN FINAL"}];
const COMPETITION_NAMES=["Liga Apertura","Liga Clausura","Liga Ronda Final","Copa Apertura","Copa Clausura"];
function emptyCup(){return {bestLosers:[null,null],stages:Object.fromEntries(CUP_STAGE_SPECS.map(stage=>[stage.key,Array.from({length:stage.count},()=>({teams:[null,null],scores:[[null,null],[null,null]],date:"",winner:null}))]))}}
function mergeCup(saved={}){const base=emptyCup();return {...base,...saved,bestLosers:Array.from({length:2},(_,i)=>saved.bestLosers?.[i]??null),stages:Object.fromEntries(CUP_STAGE_SPECS.map(stage=>[stage.key,Array.from({length:stage.count},(_,i)=>{const tie=saved.stages?.[stage.key]?.[i]||{};return {...base.stages[stage.key][i],...tie,teams:Array.from({length:2},(_,t)=>tie.teams?.[t]??null),scores:Array.from({length:2},(_,leg)=>Array.from({length:2},(_,t)=>tie.scores?.[leg]?.[t]??null))}})]))}}
const DEFAULT_DATA={league:"RONDA FINAL",season:"2026 / 2027",welcome:"",clubs:DEFAULT_CLUBS,cups:{apertura:emptyCup(),clausura:emptyCup()},leaguesCompleted:{apertura:false,clausura:false,general:false},news:[]};
const STORAGE_KEY="universoFantasyData";
const PASSWORD_KEY="universoFantasyPassword";
let data=loadData();
let currentClubIndex=0;

function loadData(){
  try{
    const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");
    let clubs=saved.clubs;
    if(!clubs&&Array.isArray(saved.teams)) clubs=saved.teams.map(name=>({name,manager:"Por asignar",points:0,crest:""}));
    clubs=DEFAULT_CLUBS.map((fallback,i)=>{const club={...fallback,...(clubs?.[i]||{})};if(club.pointsGeneral===0&&club.points)club.pointsGeneral=club.points;club.badges=Array.from({length:4},(_,b)=>({...fallback.badges[b],...(club.badges?.[b]||{})}));club.titleWins=Array.from({length:5},(_,t)=>Math.max(0,Math.min(10,Number(club.titleWins?.[t])||0)));club.players=Array.from({length:25},(_,p)=>({...fallback.players[p],...(club.players?.[p]||{})}));club.matchdays=Array.from({length:38},(_,j)=>Number(club.matchdays?.[j])||0);club.playerHistory=Array.isArray(club.playerHistory)?club.playerHistory:[];club.lineups=Array.from({length:38},(_,j)=>Array.from({length:11},(_,p)=>({name:club.lineups?.[j]?.[p]?.name||"",points:Number(club.lineups?.[j]?.[p]?.points)||0})));club.formations=Array.from({length:38},(_,j)=>club.formations?.[j]||"1-4-3-3");club.transfers=Array.isArray(club.transfers)?club.transfers:[];club.initialBalance=Number(club.initialBalance)||0;return club});
    const merged={...DEFAULT_DATA,...saved,clubs};merged.cups={apertura:mergeCup(saved.cups?.apertura),clausura:mergeCup(saved.cups?.clausura)};merged.leaguesCompleted={...DEFAULT_DATA.leaguesCompleted,...(saved.leaguesCompleted||{})};merged.news=Array.isArray(saved.news)?saved.news:[];if(merged.season==="2026 / 27")merged.season="2026 / 2027";if(merged.league==="UNIVERSO")merged.league="RONDA FINAL";return merged;
  }catch{return {...DEFAULT_DATA,clubs:DEFAULT_CLUBS.map(c=>({...c}))}}
}
function esc(value){const d=document.createElement("div");d.textContent=value;return d.innerHTML}
function initials(name,index){const words=name.trim().split(/\s+/);return words.length>1?words.slice(0,2).map(w=>w[0]).join("").toUpperCase():(name.slice(0,2)||`E${index+1}`).toUpperCase()}
function crestMarkup(club,index,className="crest"){
  return club.crest?`<img class="${className} has-image" src="${esc(club.crest)}" alt="Escudo de ${esc(club.name)}">`:`<span class="${className} ${className==='mini-crest'?'mini-fallback':''}">${esc(initials(club.name,index))}</span>`;
}
function standingsMarkup(pointsField){
  const ranked=data.clubs.map((club,index)=>({club,index})).sort((a,b)=>Number(b.club[pointsField])-Number(a.club[pointsField])||a.index-b.index);
  return ranked.map(({club,index},position)=>`<a class="standing-row" href="#club/${index}" data-club="${index}"><div class="standing-club"><span class="position">${String(position+1).padStart(2,"0")}</span>${crestMarkup(club,index,"mini-crest")}<span class="standing-name"><strong>${esc(club.name)}</strong><small>Manager · ${esc(club.manager)}</small></span></div><span class="standing-points"><b>${Number(club[pointsField])||0}</b><small>PTS</small></span></a>`).join("");
}
function compactStandingsMarkup(pointsField){const ranked=data.clubs.map((club,index)=>({club,index})).sort((a,b)=>Number(b.club[pointsField])-Number(a.club[pointsField])||a.index-b.index);return ranked.map(({club,index},position)=>`<a class="compact-standing-row" href="#club/${index}" data-club="${index}"><span class="compact-position">${String(position+1).padStart(2,"0")}</span>${club.crest?`<img class="compact-crest" src="${esc(club.crest)}" alt="">`:`<span class="compact-crest compact-fallback">${esc(initials(club.name,index))}</span>`}<strong class="compact-name">${esc(club.name)}</strong><span class="compact-points">${Number(club[pointsField])||0}<small>PTS</small></span></a>`).join("")}
function clubName(index,fallback="Equipo por sortear"){return index===null||index===undefined?fallback:(data.clubs[index]?.name||fallback)}
function scoreText(value){return value===null||value===""?"—":Number(value)}
function cupTieMarkup(label,tie){return `<article class="cup-tie"><div class="cup-tie-head"><span>${label}</span><small>${esc(tie.date||"FECHAS PENDIENTES")}</small></div>${[0,1].map(team=>`<div class="cup-team">${tie.teams[team]!==null?crestMarkup(data.clubs[tie.teams[team]],tie.teams[team],"cup-team-crest"):`<i>?</i>`}<strong>${esc(clubName(tie.teams[team]))}</strong><b>IDA <em>${scoreText(tie.scores[0][team])}</em><br>VUELTA <em>${scoreText(tie.scores[1][team])}</em></b></div>`).join("")}<div class="cup-winner">CLASIFICADO · <strong>${esc(clubName(tie.winner,"POR DECIDIR"))}</strong></div></article>`}
function cupStageMarkup(number,spec,cup){return `<section class="cup-stage ${spec.key}"><div class="cup-stage-title"><span>${number}</span><div><small>DOBLE PARTIDO</small><h3>${spec.title}</h3></div></div><div class="cup-ties">${cup.stages[spec.key].map((tie,i)=>cupTieMarkup(`${spec.prefix} ${i+1}`,tie)).join("")}</div></section>`}
function renderCupFormats(){document.querySelectorAll(".cup-format").forEach(container=>{const key=container.dataset.cup.includes("Apertura")?"apertura":"clausura",cup=data.cups[key],champion=cup.stages.final[0].winner;container.innerHTML=`<section class="cup-rules"><div><small>FORMATO OFICIAL</small><h3>DE 12 A 1 CAMPEÓN</h3></div><ol><li><b>12 equipos</b> disputan la ronda previa.</li><li><b>6 ganadores</b> pasan directamente.</li><li><b>2 mejores perdedores</b> completan los cuartos.</li><li><b>8 equipos</b> disputan el cuadro final.</li></ol><span class="dates-pending">CALENDARIO · EDITABLE</span></section>${cupStageMarkup("01",CUP_STAGE_SPECS[0],cup)}<section class="qualification-strip qualification-new"><div><small>CLASIFICAN A CUARTOS</small><strong>6 GANADORES</strong></div><i>+</i><div><small>REPESCA</small><strong>${cup.bestLosers.map(i=>esc(clubName(i,"POR DECIDIR"))).join(" · ")}</strong></div><i>=</i><div class="qualification-total"><small>CUADRO FINAL</small><strong>8 EQUIPOS</strong></div></section>${CUP_STAGE_SPECS.slice(1).map((spec,i)=>cupStageMarkup(String(i+2).padStart(2,"0"),spec,cup)).join("")}<section class="cup-champion"><span>★</span><small>CAMPEÓN DE ${esc(container.dataset.cup.toUpperCase())}</small><strong>${esc(clubName(champion,"POR DECIDIR"))}</strong><p>La copa espera dueño.</p></section>`})}
function positionCode(position){return {Portero:"POR",Defensa:"DEF",Medio:"MED",Delantero:"DEL"}[position]||"MED"}
function positionClass(position){return {Portero:"gk",Defensa:"df",Medio:"mf",Delantero:"fw"}[position]||"mf"}
function squadMarkup(club){return club.players.map((player,i)=>`<tr class="${player.name?'':'empty-player'}"><td class="squad-number">${String(i+1).padStart(2,"0")}</td><td class="player-name">${esc(player.name||`Jugador ${i+1}`)}</td><td><span class="position-tag ${positionClass(player.position)}">${positionCode(player.position)}</span></td><td class="money-value">${esc(player.marketValue||"—")}</td><td class="money-value">${esc(player.clause||"—")}</td><td class="points-value">${Number(player.points)||0}</td></tr>`).join("")}
function playersEditorMarkup(club){return `<details class="squad-editor"><summary>Plantilla de 25 jugadores</summary><p class="players-help">Introduce las cantidades con la unidad que prefieras, por ejemplo: 12 M€ o 850.000 €.</p><div class="players-editor">${club.players.map((player,p)=>`<div class="player-editor-row" data-player="${p}"><span>${String(p+1).padStart(2,"0")}</span><label>Jugador<input data-player-field="name" value="${esc(player.name)}" maxlength="40"></label><label>Posición<select data-player-field="position">${["Portero","Defensa","Medio","Delantero"].map(pos=>`<option ${player.position===pos?'selected':''}>${pos}</option>`).join("")}</select></label><label>Valor mercado<input data-player-field="marketValue" value="${esc(player.marketValue)}" maxlength="20"></label><label>Cláusula<input data-player-field="clause" value="${esc(player.clause)}" maxlength="20"></label><label>Puntos<input data-player-field="points" type="number" value="${Number(player.points)||0}"></label></div>`).join("")}</div></details>`}
const FORMATIONS=["1-4-4-2","1-4-3-3","1-3-4-3","1-3-3-4","1-5-3-2","1-5-4-1","1-4-5-1","1-3-5-2"];
function formationSpots(formation){const lines=formation.split("-").slice(1).map(Number),xs=lines.length===2?[36,76]:[29,55,82],spots=[{x:8,y:50,pos:"gk"}];lines.forEach((count,line)=>{for(let p=0;p<count;p++)spots.push({x:xs[line],y:(p+1)*100/(count+1),pos:line===0?"df":line===lines.length-1?"fw":"mf"})});return spots}
function renderLineup(club,jornada){const lineup=club.lineups[jornada],formation=club.formations[jornada],spots=formationSpots(formation);const markings=`<div class="field-markings"><i class="penalty-box left"></i><i class="goal-box left"></i><i class="penalty-box right"></i><i class="goal-box right"></i><i class="center-dot"></i></div>`;document.getElementById("footballField").innerHTML=markings+lineup.map((player,i)=>{const spot=spots[i];return `<div class="lineup-player ${spot.pos}" style="--x:${spot.x}%;--y:${spot.y}%"><span class="player-token">${i+1}</span><strong>${esc(player.name||`Jugador ${i+1}`)}</strong><small>${Number(player.points)||0} PTS</small></div>`}).join("");document.getElementById("lineupFormation").textContent=formation;document.getElementById("lineupTotal").textContent=lineup.reduce((sum,p)=>sum+(Number(p.points)||0),0)}
function lineupAdminRows(club,jornada){return club.lineups[jornada].map((player,p)=>`<div class="admin-lineup-player" data-lineup-player="${p}"><span>${p+1}</span><label>Jugador<input data-lineup-field="name" value="${esc(player.name)}" maxlength="40"></label><label>Puntos<input data-lineup-field="points" type="number" step="0.01" value="${Number(player.points)||0}"></label></div>`).join("")}
function lineupEditorMarkup(club,i){return `<details class="lineup-admin"><summary>Alineaciones por jornada</summary><div class="admin-lineup-toolbar"><label>Jornada<select data-lineup-select="${i}">${Array.from({length:38},(_,j)=>`<option value="${j}">Jornada ${j+1}</option>`).join("")}</select></label><label>Formación<select data-formation-select="${i}">${FORMATIONS.map(f=>`<option ${club.formations[0]===f?'selected':''}>${f}</option>`).join("")}</select></label></div><div class="admin-lineup-grid">${lineupAdminRows(club,0)}</div></details>`}
function numericPrice(value){if(typeof value==="number")return value;return Number(String(value||0).replace(/[^0-9,.-]/g,"").replace(",","."))||0}
function formatMoney(value){return new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(value)||0)}
function transferEditorRow(item={player:"",type:"Comprado",price:0}){return `<div class="transfer-editor-row"><label>Jugador<input data-transfer-field="player" value="${esc(item.player)}" maxlength="40"></label><label>Operación<select data-transfer-field="type"><option ${item.type==="Comprado"?'selected':''}>Comprado</option><option ${item.type==="Vendido"?'selected':''}>Vendido</option></select></label><label class="transfer-price-input">Precio<input data-transfer-field="price" type="number" min="0" step="1" value="${numericPrice(item.price)}"></label><button class="transfer-remove" type="button">×</button></div>`}
function transfersEditorMarkup(club){return `<details class="transfers-admin"><summary>Economía, compras y ventas</summary><div class="balance-admin"><label>Saldo inicial (€)<input data-initial-balance type="number" min="0" step="1" value="${Number(club.initialBalance)||0}"></label><p>Las compras restan y las ventas suman automáticamente al saldo del manager.</p></div><div class="transfers-editor-list">${club.transfers.map(transferEditorRow).join("")}</div><button class="transfer-add" type="button">＋ AÑADIR OPERACIÓN</button></details>`}
function renderTransfers(club){const items=club.transfers.filter(t=>t.player);document.getElementById("transfersList").innerHTML=items.map((item,i)=>`<tr><td class="transfer-number">${String(i+1).padStart(2,"0")}</td><td class="transfer-player">${esc(item.player)}</td><td><span class="transfer-type ${item.type==='Vendido'?'sell':'buy'}">${esc(item.type)}</span></td><td class="transfer-price">${formatMoney(numericPrice(item.price))}</td></tr>`).join("");document.getElementById("transfersEmpty").hidden=items.length>0;document.querySelector(".transfers-table").hidden=items.length===0;const movement=items.reduce((sum,item)=>sum+(item.type==="Vendido"?numericPrice(item.price):-numericPrice(item.price)),0);document.getElementById("managerBalance").textContent=formatMoney(club.initialBalance+movement);document.getElementById("balanceMovement").textContent=`Inicial ${formatMoney(club.initialBalance)} · Movimientos ${movement>=0?'+':''}${formatMoney(movement)}`}
function matchdaysEditorMarkup(club){const block=(start,end,title)=>`<div class="admin-round"><span class="admin-round-title">${title}</span>${club.matchdays.slice(start,end).map((points,offset)=>{const j=start+offset;return `<label>Jornada ${j+1}<input data-matchday="${j}" type="number" step="0.01" value="${Number(points)||0}"></label>`}).join("")}</div>`;return `<details class="matchdays-editor"><summary>Puntos por jornada</summary><p class="matchday-help">Registra la puntuación numérica de Apertura y Clausura.</p><div class="matchday-inputs">${block(0,19,"Apertura · J1–J19")}${block(19,38,"Clausura · J20–J38")}</div></details>`}
function historyEditorMarkup(club){return `<details class="history-editor"><summary>Histórico de jugadores utilizados</summary><p class="matchday-help">Añade todos los futbolistas que hayan participado con el club, aunque ya no estén en la plantilla.</p><div class="history-editor-list">${club.playerHistory.map(player=>historyEditorRow(player)).join("")}</div><button class="history-add" type="button">＋ AÑADIR JUGADOR AL HISTÓRICO</button></details>`}
function historyEditorRow(player={name:"",points:0}){return `<div class="history-editor-row"><label>Jugador<input data-history-field="name" value="${esc(player.name)}" maxlength="40"></label><label>Puntos<input data-history-field="points" type="number" step="0.01" value="${Number(player.points)||0}"></label><button class="history-remove" type="button" aria-label="Eliminar">×</button></div>`}
function renderHistory(club){const direction=document.getElementById("historySort").value==="asc"?1:-1;const players=[...club.playerHistory].filter(p=>p.name).sort((a,b)=>(Number(a.points)-Number(b.points))*direction||a.name.localeCompare(b.name));document.getElementById("historyList").innerHTML=players.map((player,i)=>`<tr><td class="history-rank">${String(i+1).padStart(2,"0")}</td><td class="history-name">${esc(player.name)}</td><td class="history-points">${Number(player.points)||0}<small>PTS</small></td></tr>`).join("");document.getElementById("historyEmpty").hidden=players.length>0;document.querySelector(".history-table").hidden=players.length===0}
function renderMatchdays(club){const values=club.matchdays.map(Number);document.getElementById("matchdaysTotal").textContent=values.reduce((sum,value)=>sum+value,0).toLocaleString("es-ES");const best=Math.max(...values),worst=Math.min(...values),bestIndex=values.indexOf(best),worstIndex=values.indexOf(worst);document.getElementById("bestMatchdayPoints").textContent=best;document.getElementById("worstMatchdayPoints").textContent=worst;document.getElementById("bestMatchdayLabel").textContent=`Jornada ${bestIndex+1}`;document.getElementById("worstMatchdayLabel").textContent=`Jornada ${worstIndex+1}`;const max=Math.max(10,...values);const roundedMax=Math.ceil(max/10)*10;document.getElementById("chartScale").innerHTML=`<span>${roundedMax}</span><span>${Math.round(roundedMax*.75)}</span><span>${Math.round(roundedMax*.5)}</span><span>${Math.round(roundedMax*.25)}</span><span>0</span>`;document.getElementById("matchdaysChart").innerHTML=values.map((points,j)=>`<div class="chart-column"><div class="chart-bar" style="height:${Math.max(0,points)/roundedMax*100}%" data-tooltip="J${j+1}: ${points} pts"></div><span class="chart-label">${j+1}</span></div>`).join("");const rows=(start,end)=>values.slice(start,end).map((points,offset)=>{const jornada=start+offset+1;return `<div class="round-row"><span class="round-number">JORNADA ${jornada}</span><strong class="round-score">${points}<small>PTS</small></strong></div>`}).join("");document.getElementById("aperturaMatchdays").innerHTML=rows(0,19);document.getElementById("clausuraMatchdays").innerHTML=rows(19,38)}
function leagueBonus(field,top,step){const order=data.clubs.map((club,index)=>({index,points:Number(club[field])||0})).sort((a,b)=>b.points-a.points||a.index-b.index);return Object.fromEntries(order.map((entry,pos)=>[entry.index,pos<3?top[pos]:Math.max(0,top[2]-step*(pos-2))]))}
function cupWins(index){return Object.values(data.cups).reduce((total,cup)=>total+CUP_STAGE_SPECS.reduce((sum,stage)=>sum+cup.stages[stage.key].filter(tie=>tie.winner===index).length,0),0)}
function rankingRows(){const ap=leagueBonus("pointsApertura",[600,400,300],25),cl=leagueBonus("pointsClausura",[600,400,300],25),rf=leagueBonus("pointsGeneral",[1200,800,600],50),done=data.leaguesCompleted;return data.clubs.map((club,index)=>{const participation=(done.apertura?(Number(club.pointsApertura)||0):0)+(done.clausura?(Number(club.pointsClausura)||0):0)+(done.general?(Number(club.pointsGeneral)||0):0),league=(done.apertura?ap[index]:0)+(done.clausura?cl[index]:0)+(done.general?rf[index]:0),cups=cupWins(index)*50;return {club,index,participation,league,cups,total:participation+league+cups}}).sort((a,b)=>b.total-a.total||a.index-b.index)}
function renderRanking(){document.getElementById("rankingRfList").innerHTML=rankingRows().map((row,pos)=>`<a class="ranking-row" href="#club/${row.index}" data-club="${row.index}"><div class="ranking-club"><b>${String(pos+1).padStart(2,"0")}</b>${crestMarkup(row.club,row.index,"mini-crest")}<span><strong>${esc(row.club.name)}</strong><small>${esc(row.club.manager)}</small></span></div><span>${row.participation}<small>PR</small></span><span>${row.league}<small>PR</small></span><span>${row.cups}<small>PR</small></span><strong>${row.total}<small>PR</small></strong></a>`).join("")}
const TITLE_BADGE_VISUALS=[
  {code:"LA",subtitle:"APERTURA",icon:`<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="34" r="12"/><path d="M32 7v10M32 51v8M5 34h10M49 34h10M13 15l8 8M43 45l8 8M51 15l-8 8M21 45l-8 8"/></svg>`},
  {code:"LC",subtitle:"CLAUSURA",icon:`<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M44 49A23 23 0 1 1 39 9c-13 5-17 22-8 32 4 5 9 7 13 8Z"/></svg>`},
  {code:"RF",subtitle:"REINA",icon:`<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M10 20l12 10 10-18 10 18 12-10-5 29H15Z"/><path d="M16 54h32"/></svg>`},
  {code:"CA",subtitle:"COPA APERTURA",icon:`<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M20 10h24v12c0 12-5 19-12 19s-12-7-12-19Z"/><path d="M20 15H9c0 12 5 17 14 17M44 15h11c0 12-5 17-14 17M32 41v10M21 55h22"/></svg>`},
  {code:"CC",subtitle:"COPA CLAUSURA",icon:`<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M20 10h24v12c0 12-5 19-12 19s-12-7-12-19Z"/><path d="M20 15H9c0 12 5 17 14 17M44 15h11c0 12-5 17-14 17M32 41v10M21 55h22"/></svg>`}
];
function titleBadgeMarkup(name,count,index){const visual=TITLE_BADGE_VISUALS[index],stars=Array.from({length:10},(_,i)=>`<i class="${i<count?'won':''}" style="--i:${i}">★</i>`).join("");return `<div class="title-badge title-badge-${index}"><div class="title-emblem"><div class="title-stars">${stars}</div><div class="title-medal">${visual.icon}<span>${visual.code}</span><b>${visual.subtitle}</b></div></div><strong>${esc(name)}</strong><small>${count} ${count===1?'TÍTULO':'TÍTULOS'}</small></div>`}
function teamOption(value,selected,label="Seleccionar equipo"){return `<option value="${value??''}" ${String(selected??'')===String(value??'')?'selected':''}>${esc(label)}</option>`}
function clubOptions(selected){return teamOption(null,selected)+data.clubs.map((club,i)=>teamOption(i,selected,club.name)).join("")}
function cupTieEditor(tie,stageKey,index){return `<div class="cup-tie-editor" data-stage="${stageKey}" data-tie="${index}"><strong>ELIMINATORIA ${index+1}</strong><label>Fecha / jornada<input data-cup-field="date" value="${esc(tie.date)}" placeholder="Pendiente"></label>${[0,1].map(team=>`<div class="cup-editor-team"><label>Equipo ${team+1}<select data-cup-team="${team}">${clubOptions(tie.teams[team])}</select></label><label>Ida<input data-cup-score="0:${team}" type="number" min="0" value="${tie.scores[0][team]??''}"></label><label>Vuelta<input data-cup-score="1:${team}" type="number" min="0" value="${tie.scores[1][team]??''}"></label></div>`).join("")}<label>Clasificado<select data-cup-field="winner">${clubOptions(tie.winner)}</select></label></div>`}
function renderCupAdmin(){document.getElementById("cupAdminEditors").innerHTML=Object.entries(data.cups).map(([key,cup])=>`<details class="cup-admin" data-cup-admin="${key}"><summary>Copa ${key==='apertura'?'Apertura':'Clausura'}</summary><div class="cup-special-editor">${cup.bestLosers.map((team,i)=>`<label>Mejor perdedor ${i+1}<select data-cup-loser="${i}">${clubOptions(team)}</select></label>`).join("")}</div>${CUP_STAGE_SPECS.map(stage=>`<section><h4>${stage.title}</h4><div class="cup-admin-grid">${cup.stages[stage.key].map((tie,i)=>cupTieEditor(tie,stage.key,i)).join("")}</div></section>`).join("")}</details>`).join("")}
function safeNewsUrl(value){const url=String(value||"").trim();return /^(https?:\/\/|#)/i.test(url)?url:""}
function renderNews(){const grid=document.getElementById("homeNewsGrid");if(!data.news.length){grid.innerHTML=`<div class="news-empty"><span>RF</span><div><strong>PRÓXIMAMENTE</strong><p>Las noticias, novedades y eventos oficiales aparecerán aquí.</p></div></div>`;return}grid.innerHTML=data.news.map((item,index)=>{const url=safeNewsUrl(item.link),tag=esc(item.category||"NOTICIA");return `<article class="news-card news-card-${index%3}"><div class="news-meta"><span>${tag}</span><time>${esc(item.date||"FECHA POR CONFIRMAR")}</time></div><h3>${esc(item.title||"Sin título")}</h3><p>${esc(item.body||"")}</p>${url?`<a href="${esc(url)}" ${url.startsWith('http')?'target="_blank" rel="noopener"':''}>MÁS INFORMACIÓN →</a>`:""}</article>`}).join("")}
function newsEditorRow(item={category:"Noticia",date:"",title:"",body:"",link:""}){return `<div class="news-editor-row"><div class="news-editor-top"><label>Categoría<select data-news-field="category">${["Noticia","Novedad","Evento","Aviso"].map(value=>`<option ${item.category===value?'selected':''}>${value}</option>`).join("")}</select></label><label>Fecha<input data-news-field="date" type="date" value="${esc(item.date)}"></label><button class="news-remove" type="button" aria-label="Eliminar publicación">×</button></div><label>Título<input data-news-field="title" value="${esc(item.title)}" maxlength="80"></label><label>Texto<textarea data-news-field="body" rows="3" maxlength="320">${esc(item.body)}</textarea></label><label>Enlace opcional<input data-news-field="link" value="${esc(item.link)}" placeholder="https://..."></label></div>`}
function renderNewsAdmin(){document.getElementById("newsAdminList").innerHTML=data.news.map(newsEditorRow).join("")}
function render(){
  document.getElementById("brandName").textContent=data.league;
  document.getElementById("seasonText").textContent=data.season;
  document.getElementById("welcomeText").textContent=data.welcome;
  document.title=data.league;
  document.getElementById("teamsGrid").innerHTML=data.clubs.map((club,i)=>`<a class="team-card" href="#club/${i}" data-club="${i}"><span class="team-number">${String(i+1).padStart(2,"0")}</span>${crestMarkup(club,i)}<h3>${esc(club.name)}</h3><div class="card-manager"><span>MANAGER</span><strong>${esc(club.manager)}</strong></div><span class="team-arrow">→</span></a>`).join("");
  document.getElementById("aperturaList").innerHTML=standingsMarkup("pointsApertura");
  document.getElementById("clausuraList").innerHTML=standingsMarkup("pointsClausura");
  document.getElementById("generalList").innerHTML=standingsMarkup("pointsGeneral");
  renderCupFormats();
  renderRanking();
  renderNews();
  renderTeamEditors();
  renderCupAdmin();
  renderBadgeLibraries();
}
const BADGE_PRESETS={fundador:{name:"Equipo Fundador",image:"imagenes/insignias/equipo_fundador_512.png"},mejor:{name:"Mejor Jornada",image:"imagenes/insignias/mejor_jornada_512.png"},peor:{name:"Peor Jornada",image:"imagenes/insignias/peor_jornada_512.png"}};
function renderBadgeLibraries(){document.querySelectorAll(".badge-editor").forEach((details,i)=>{const buttons=Object.entries(BADGE_PRESETS).map(([key,badge])=>`<button class="badge-preset" type="button" data-badge-preset="${key}" data-club="${i}"><img src="${badge.image}" alt="">${badge.name}</button>`).join("");const library=`<div class="badge-library"><small>INSIGNIAS DISPONIBLES</small>${buttons}</div>`;details.querySelector("summary").insertAdjacentHTML("afterend",library)})}
function renderTeamEditors(){
  document.getElementById("teamInputs").innerHTML=data.clubs.map((club,i)=>`<div class="team-editor" data-editor="${i}"><span class="team-editor-title">CLUB ${String(i+1).padStart(2,"0")}</span>${club.crest?`<img class="upload-preview" src="${esc(club.crest)}" alt="">`:""}<label>Nombre<input data-field="name" value="${esc(club.name)}" maxlength="32"></label><label>Manager<input data-field="manager" value="${esc(club.manager)}" maxlength="40"></label><div class="points-editor"><label>Liga Apertura<input data-field="pointsApertura" type="number" min="0" step="1" value="${Number(club.pointsApertura)||0}"></label><label>Liga Clausura<input data-field="pointsClausura" type="number" min="0" step="1" value="${Number(club.pointsClausura)||0}"></label><label>Liga Ronda Final<input data-field="pointsGeneral" type="number" min="0" step="1" value="${Number(club.pointsGeneral)||0}"></label></div><details class="title-wins-editor"><summary>Títulos e insignias oficiales</summary>${COMPETITION_NAMES.map((name,t)=>`<label>${name}<input data-title-win="${t}" type="number" min="0" max="10" value="${club.titleWins[t]}"></label>`).join("")}</details><label>Escudo 512 × 512<input data-crest-input="${i}" type="file" accept="image/png,image/jpeg,image/webp"></label><p class="upload-help">PNG, JPG o WebP. Recomendado: 512 × 512 y menos de 1 MB.</p><details class="badge-editor"><summary>Otras insignias del club</summary>${club.badges.map((badge,b)=>`<div class="badge-field">${badge.image?`<img src="${esc(badge.image)}" alt="">`:""}<label>Insignia ${b+1}<input data-badge-name="${b}" value="${esc(badge.name)}" placeholder="Ej: Equipo Fundador" maxlength="32"></label><label>Icono<input data-badge-input="${i}:${b}" type="file" accept="image/png,image/jpeg,image/webp"></label></div>`).join("")}</details>${lineupEditorMarkup(club,i)}${transfersEditorMarkup(club)}${matchdaysEditorMarkup(club)}${historyEditorMarkup(club)}</div>`).join("");
}
function navigate(route){
  document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));
  const isClub=route.startsWith("club/");
  const target=isClub?"club":(["inicio","equipos","apertura","clausura","liga-general","copa-apertura","copa-clausura","ranking-rf"].includes(route)?route:"inicio");
  document.getElementById(target).classList.add("active");
  document.querySelectorAll(".nav a").forEach(a=>a.classList.toggle("active",a.dataset.route===target));
  if(isClub){
    const index=Number(route.split("/")[1]);const club=data.clubs[index];
    if(club){currentClubIndex=index;
      document.getElementById("clubName").textContent=club.name;
      document.getElementById("clubManager").textContent=club.manager;
      const lineupSelect=document.getElementById("lineupMatchday");lineupSelect.innerHTML=Array.from({length:38},(_,j)=>`<option value="${j}">Jornada ${j+1}</option>`).join("");lineupSelect.value=0;renderLineup(club,0);renderTransfers(club);
      renderMatchdays(club);
      renderHistory(club);
      const activeBadges=club.badges.filter(b=>b.name||b.image);document.getElementById("clubBadges").innerHTML=`<div class="official-title-badges">${COMPETITION_NAMES.map((name,t)=>titleBadgeMarkup(name,club.titleWins[t],t)).join("")}</div>${activeBadges.map(b=>`<div class="club-badge">${b.image?`<img src="${esc(b.image)}" alt="${esc(b.name||'Insignia')}">`:`<span class="badge-placeholder">★</span>`}<strong>${esc(b.name||"Insignia")}</strong></div>`).join("")}`;
      const crest=document.getElementById("clubCrest");crest.textContent=club.crest?"":initials(club.name,index);crest.classList.toggle("has-image",Boolean(club.crest));crest.style.backgroundImage=club.crest?`url("${club.crest}")`:"";crest.style.backgroundSize="contain";crest.style.backgroundPosition="center";crest.style.backgroundRepeat="no-repeat";
    }
  }
  document.getElementById("mainNav").classList.remove("open");window.scrollTo(0,0);
}
document.addEventListener("click",e=>{const route=e.target.closest("[data-route]");if(route){e.preventDefault();location.hash=route.dataset.route}const club=e.target.closest("[data-club]");if(club){e.preventDefault();location.hash=`club/${club.dataset.club}`}});
window.addEventListener("hashchange",()=>navigate(location.hash.slice(1)||"inicio"));
document.getElementById("historySort").addEventListener("change",()=>renderHistory(data.clubs[currentClubIndex]));
document.getElementById("lineupMatchday").addEventListener("change",e=>renderLineup(data.clubs[currentClubIndex],Number(e.target.value)));
document.getElementById("menuToggle").addEventListener("click",()=>document.getElementById("mainNav").classList.toggle("open"));

const modal=document.getElementById("adminModal");
function openModal(){modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.getElementById("password").focus()}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.getElementById("loginError").textContent=""}
function enterAdmin(){
  document.getElementById("loginView").hidden=true;document.getElementById("editorView").hidden=false;
  document.getElementById("editLeague").value=data.league;document.getElementById("editSeason").value=data.season;document.getElementById("editWelcome").value=data.welcome;document.getElementById("completedApertura").checked=data.leaguesCompleted.apertura;document.getElementById("completedClausura").checked=data.leaguesCompleted.clausura;document.getElementById("completedGeneral").checked=data.leaguesCompleted.general;renderNewsAdmin();renderTeamEditors();renderBadgeLibraries();
}
window.enterAdmin=enterAdmin;
document.getElementById("adminOpen").addEventListener("click",openModal);
document.getElementById("adminClose").addEventListener("click",closeModal);
modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
document.getElementById("loginForm").addEventListener("submit",async e=>{
  e.preventDefault();const password=document.getElementById("password").value,errorBox=document.getElementById("loginError");
  if(window.remoteEnabled){try{await remoteLogin(password)}catch(error){errorBox.textContent=error.message||"No se pudo iniciar sesión.";return}}
  else{const saved=localStorage.getItem(PASSWORD_KEY)||"cambiar-esta-clave";if(password!==saved){errorBox.textContent="Contraseña incorrecta.";return}}
  enterAdmin();
});
document.getElementById("teamInputs").addEventListener("change",async e=>{
  const input=e.target.closest("[data-crest-input],[data-badge-input]");if(!input||!input.files[0])return;
  const file=input.files[0];
  if(file.size>1500000){alert("El archivo es demasiado grande. Usa una imagen de menos de 1,5 MB.");input.value="";return}
  if(window.remoteEnabled){try{const isCrest=input.hasAttribute("data-crest-input"),assetUrl=await uploadLeagueAsset(file,isCrest?"escudos":"insignias");if(isCrest){data.clubs[Number(input.dataset.crestInput)].crest=assetUrl;const old=input.closest(".team-editor").querySelector(".upload-preview");if(old)old.remove();const preview=document.createElement("img");preview.className="upload-preview";preview.src=assetUrl;input.closest(".team-editor").prepend(preview)}else{const [clubIndex,badgeIndex]=input.dataset.badgeInput.split(":").map(Number);data.clubs[clubIndex].badges[badgeIndex].image=assetUrl;const field=input.closest(".badge-field"),old=field.querySelector("img");if(old)old.remove();const preview=document.createElement("img");preview.src=assetUrl;field.prepend(preview)}return}catch(error){alert(`No se pudo subir la imagen: ${error.message}`);return}}
  const image=new Image();const reader=new FileReader();
  reader.onload=()=>{image.onload=()=>{if(input.hasAttribute("data-crest-input")){if(image.width!==512||image.height!==512){alert(`El escudo mide ${image.width} × ${image.height}. Se recomienda 512 × 512, aunque puedes guardarlo igualmente.`)}data.clubs[Number(input.dataset.crestInput)].crest=reader.result;const old=input.closest(".team-editor").querySelector(".upload-preview");if(old)old.remove();const preview=document.createElement("img");preview.className="upload-preview";preview.src=reader.result;input.closest(".team-editor").prepend(preview)}else{const [clubIndex,badgeIndex]=input.dataset.badgeInput.split(":").map(Number);data.clubs[clubIndex].badges[badgeIndex].image=reader.result;const field=input.closest(".badge-field");const old=field.querySelector("img");if(old)old.remove();const preview=document.createElement("img");preview.src=reader.result;field.prepend(preview)}};image.src=reader.result};reader.readAsDataURL(file);
});
document.getElementById("teamInputs").addEventListener("change",e=>{const select=e.target.closest("[data-lineup-select]");if(select){const editor=select.closest("[data-editor]"),club=data.clubs[Number(editor.dataset.editor)],jornada=Number(select.value);editor.querySelector(".admin-lineup-grid").innerHTML=lineupAdminRows(club,jornada);editor.querySelector("[data-formation-select]").value=club.formations[jornada];return}const formation=e.target.closest("[data-formation-select]");if(formation){const editor=formation.closest("[data-editor]"),jornada=Number(editor.querySelector("[data-lineup-select]").value);data.clubs[Number(editor.dataset.editor)].formations[jornada]=formation.value}});
document.getElementById("teamInputs").addEventListener("input",e=>{const input=e.target.closest("[data-lineup-field]");if(!input)return;const editor=input.closest("[data-editor]"),playerRow=input.closest("[data-lineup-player]"),jornada=Number(editor.querySelector("[data-lineup-select]").value);const player=data.clubs[Number(editor.dataset.editor)].lineups[jornada][Number(playerRow.dataset.lineupPlayer)];player[input.dataset.lineupField]=input.dataset.lineupField==="points"?Number(input.value)||0:input.value});
document.getElementById("teamInputs").addEventListener("click",e=>{const preset=e.target.closest("[data-badge-preset]");if(preset){const club=data.clubs[Number(preset.dataset.club)],badge=club.badges.find(b=>!b.name&&!b.image),selected=BADGE_PRESETS[preset.dataset.badgePreset];if(!badge){alert("Este club ya tiene ocupadas sus cuatro insignias.");return}badge.name=selected.name;badge.image=selected.image;renderTeamEditors();renderBadgeLibraries();return}const add=e.target.closest(".history-add");if(add){add.previousElementSibling.insertAdjacentHTML("beforeend",historyEditorRow());return}const remove=e.target.closest(".history-remove");if(remove){remove.closest(".history-editor-row").remove();return}const transferAdd=e.target.closest(".transfer-add");if(transferAdd){transferAdd.previousElementSibling.insertAdjacentHTML("beforeend",transferEditorRow());return}const transferRemove=e.target.closest(".transfer-remove");if(transferRemove)transferRemove.closest(".transfer-editor-row").remove()});
document.querySelector(".news-add").addEventListener("click",()=>document.getElementById("newsAdminList").insertAdjacentHTML("beforeend",newsEditorRow()));
document.getElementById("newsAdminList").addEventListener("click",e=>{const remove=e.target.closest(".news-remove");if(remove)remove.closest(".news-editor-row").remove()});
function optionalIndex(value){return value===""?null:Number(value)}
function readCupEditors(){document.querySelectorAll("[data-cup-admin]").forEach(editor=>{const cup=data.cups[editor.dataset.cupAdmin];editor.querySelectorAll("[data-cup-loser]").forEach(select=>cup.bestLosers[Number(select.dataset.cupLoser)]=optionalIndex(select.value));editor.querySelectorAll(".cup-tie-editor").forEach(row=>{const tie=cup.stages[row.dataset.stage][Number(row.dataset.tie)];row.querySelectorAll("[data-cup-team]").forEach(select=>tie.teams[Number(select.dataset.cupTeam)]=optionalIndex(select.value));row.querySelectorAll("[data-cup-score]").forEach(input=>{const [leg,team]=input.dataset.cupScore.split(":").map(Number);tie.scores[leg][team]=input.value===""?null:Math.max(0,Number(input.value)||0)});tie.date=row.querySelector('[data-cup-field="date"]').value.trim();tie.winner=optionalIndex(row.querySelector('[data-cup-field="winner"]').value)})})}
document.getElementById("editorForm").addEventListener("submit",async e=>{
  e.preventDefault();data.league=document.getElementById("editLeague").value.trim()||DEFAULT_DATA.league;data.season=document.getElementById("editSeason").value.trim()||DEFAULT_DATA.season;data.welcome=document.getElementById("editWelcome").value.trim()||DEFAULT_DATA.welcome;data.leaguesCompleted={apertura:document.getElementById("completedApertura").checked,clausura:document.getElementById("completedClausura").checked,general:document.getElementById("completedGeneral").checked};
  document.querySelectorAll("[data-editor]").forEach(editor=>{const index=Number(editor.dataset.editor);data.clubs[index].name=editor.querySelector('[data-field="name"]').value.trim()||`Equipo ${index+1}`;data.clubs[index].manager=editor.querySelector('[data-field="manager"]').value.trim()||"Por asignar";["pointsApertura","pointsClausura","pointsGeneral"].forEach(field=>data.clubs[index][field]=Math.max(0,Number(editor.querySelector(`[data-field="${field}"]`).value)||0));editor.querySelectorAll("[data-badge-name]").forEach(input=>data.clubs[index].badges[Number(input.dataset.badgeName)].name=input.value.trim());editor.querySelectorAll("[data-player]").forEach(row=>{const player=data.clubs[index].players[Number(row.dataset.player)];row.querySelectorAll("[data-player-field]").forEach(input=>player[input.dataset.playerField]=input.dataset.playerField==="points"?Number(input.value)||0:input.value.trim())});editor.querySelectorAll("[data-matchday]").forEach(input=>data.clubs[index].matchdays[Number(input.dataset.matchday)]=Number(input.value)||0);data.clubs[index].playerHistory=[...editor.querySelectorAll(".history-editor-row")].map(row=>({name:row.querySelector('[data-history-field="name"]').value.trim(),points:Number(row.querySelector('[data-history-field="points"]').value)||0})).filter(player=>player.name)});
  document.querySelectorAll("[data-editor]").forEach(editor=>{const index=Number(editor.dataset.editor);editor.querySelectorAll("[data-title-win]").forEach(input=>data.clubs[index].titleWins[Number(input.dataset.titleWin)]=Math.max(0,Math.min(10,Number(input.value)||0)));data.clubs[index].initialBalance=Math.max(0,Number(editor.querySelector("[data-initial-balance]").value)||0);data.clubs[index].transfers=[...editor.querySelectorAll(".transfer-editor-row")].map(row=>({player:row.querySelector('[data-transfer-field="player"]').value.trim(),type:row.querySelector('[data-transfer-field="type"]').value,price:Math.max(0,Number(row.querySelector('[data-transfer-field="price"]').value)||0)})).filter(item=>item.player)});
  data.news=[...document.querySelectorAll(".news-editor-row")].map(row=>Object.fromEntries([...row.querySelectorAll("[data-news-field]")].map(input=>[input.dataset.newsField,input.value.trim()]))).filter(item=>item.title||item.body);readCupEditors();
  try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));if(window.remoteEnabled)await remoteSave();render();document.getElementById("saveMessage").textContent="Cambios guardados online correctamente."}catch(error){document.getElementById("saveMessage").textContent=`No se pudo guardar: ${error.message||"error desconocido"}`}setTimeout(()=>document.getElementById("saveMessage").textContent="",4000);
});
document.getElementById("changePassword").addEventListener("click",async()=>{const next=prompt("Escribe tu nueva contraseña (mínimo 8 caracteres):");if(next&&next.length>=8){try{if(window.remoteEnabled)await remoteChangePassword(next);else localStorage.setItem(PASSWORD_KEY,next);alert("Contraseña actualizada correctamente.")}catch(error){alert(`No se pudo cambiar: ${error.message}`)}}else if(next!==null){alert("La contraseña debe tener al menos 8 caracteres.")}});
render();navigate(location.hash.slice(1)||"inicio");
